using DiaEditCore.Algorithm;
using DiaEditCore.Commands;
using DiaEditCore.Commands.TimeTable.Trains;
using DiaEditCore.Model;
using DiaEditCore.Model.Routes;
using DiaEditCore.Model.TimeTable;
using DiaEditCore.Model.TimeTable.Trains;
using DiaEditCore.Session;

using Xunit;

namespace DiaEditCore.Tests.Commands.TimeTable.Trains;

public class SyncRunSegmentsToTrainCommandTests
{
    // -----------------------------
    // フィクスチャ（TrainValidatorTests.csと同一パターン）
    // -----------------------------

    private static readonly ValidationRules DefaultValidationRules = new(
        MinDwellTimeSec: null,
        MinHeadwaySec: null,
        MinTurnaroundSec: null,
        TrackEntryMarginSec: null,
        TrackPassMarginSec: null,
        EnableConflictDetection: true,
        EnableCarLengthCheck: true);

    /// <summary>
    /// 空プロジェクトに指定したTrainのみを積んだProjectSessionを構築する（ProjectSessionTests.csと同一パターン）。
    /// StopKeyReferenceIndex等のキャッシュはCommand.Create()呼び出し時にこのSessionから
    /// Model層データ（ここではallTrains）を起点として自然に構築される。
    /// </summary>
    private static ProjectSession MakeSession(params Train[] allTrains)
    {
        var project = new ProjectFile
        {
            SchemaVersion = 1,
            ProjectSettings = new ProjectSettings(DefaultValidationRules),
        };
        foreach (var t in allTrains)
        {
            project.Trains.Add(t);
        }

        var session = new ProjectSession(new CommandInvoker());
        session.Load(project);
        return session;
    }

    private static MainRoute MakeMainRoute(int id, params StationId[] stationOrder) => new()
    {
        Id = new MainRouteId(id),
        Name = new DisplayName { Name = "テスト本線" },
        StationOrder = stationOrder.ToList(),
        IsLoop = false,
    };

    private static ServiceRoute MakeServiceRoute(int id, params ServiceRouteSegment[] segments) => new()
    {
        Id = new ServiceRouteId(id),
        Name = new DisplayName { Name = "テスト系統" },
        IsAutoGenerated = false,
        Segments = segments.ToList(),
    };

    private static ServiceRouteSegment MakeSrSegment(
        int mainRouteId, int fromIndex, int toIndex, StationConnectionId? selected = null) => new()
    {
        MainRouteId = new MainRouteId(mainRouteId),
        FromStationIndex = fromIndex,
        ToStationIndex = toIndex,
        SelectedStationConnectionId = selected,
    };

    private static Train MakeValidTrain(int id, string trainNumber = "1234M") => new()
    {
        Id = new TrainId(id),
        TimeTableSetId = new TimeTableSetId(1),
        TrainNumber = trainNumber,
        ServiceRouteId = new ServiceRouteId(1),
        TrainTypeId = new TrainTypeId(1),
        TrainTypeName = new DisplayName { Name = "普通" },
        Nickname = new DisplayName { Name = "" },
        DefaultVehicleTypeId = new VehicleTypeId(1),
    };

    private static StationConnectionSegment MakeSegment(int id, StationId from, StationId to, int mainRouteId = 1) => new()
    {
        Id = new StationConnectionSegmentId(id),
        FromStationId = from,
        ToStationId = to,
        FromEntryPointId = new EntryPointId(id * 10 + 1),
        ToEntryPointId = new EntryPointId(id * 10 + 2),
        MainRouteId = new MainRouteId(mainRouteId),
        BaseRunTimeSec = 60,
    };

    private static StationConnection MakeConnection(
        int id, int mainRouteId, StationConnectionDirection direction, params StationConnectionSegmentId[] segmentIds) => new()
    {
        Id = new StationConnectionId(id),
        Name = "test-sc",
        MainRouteId = new MainRouteId(mainRouteId),
        Direction = direction,
        Segments = segmentIds.ToList(),
    };

    private static readonly StationId StA = new(1);
    private static readonly StationId StB = new(2);
    private static readonly StationId StC = new(3);
    private static readonly StationId StD = new(4);

    // -----------------------------
    // 基本ケース：一致済みなら実質変化なし
    // -----------------------------

    [Fact]
    public void RunSegmentsが既に最新StationOrderと一致していれば内容は変化しない()
    {
        var mainRoute = MakeMainRoute(1, StA, StB, StC);
        var seg1 = MakeSegment(1, StA, StB);
        var seg2 = MakeSegment(2, StB, StC);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg1.Id, seg2.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 2, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StB, ToStationId = StC, StationConnectionId = sc.Id });

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg1, seg2], session);
        command.Execute();

        Assert.Equal(2, train.RunSegments.Count);
        Assert.Equal((StA, StB, sc.Id), (train.RunSegments[0].FromStationId, train.RunSegments[0].ToStationId, train.RunSegments[0].StationConnectionId));
        Assert.Equal((StB, StC, sc.Id), (train.RunSegments[1].FromStationId, train.RunSegments[1].ToStationId, train.RunSegments[1].StationConnectionId));
    }

    // -----------------------------
    // 駅の追加・削除
    // -----------------------------

    [Fact]
    public void StationOrderに駅が追加されると新規ホップが挿入される()
    {
        // 旧: A-B-C 、新: A-B-D-C（B-C間にDが挿入）
        var mainRoute = MakeMainRoute(1, StA, StB, StD, StC);
        var seg1 = MakeSegment(1, StA, StB);
        var seg2 = MakeSegment(2, StB, StD);
        var seg3 = MakeSegment(3, StD, StC);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg1.Id, seg2.Id, seg3.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 3, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StB, ToStationId = StC, StationConnectionId = sc.Id }); // 旧ホップ

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg1, seg2, seg3], session);
        command.Execute();

        Assert.Equal(3, train.RunSegments.Count);
        Assert.Equal(StB, train.RunSegments[1].FromStationId);
        Assert.Equal(StD, train.RunSegments[1].ToStationId);
        Assert.Equal(StD, train.RunSegments[2].FromStationId);
        Assert.Equal(StC, train.RunSegments[2].ToStationId);
    }

    [Fact]
    public void 駅が削除され孤立したStopTimeはWorksの有無に関わらず無条件破棄される()
    {
        // 旧: A-B-C 、新: A-C（Bが削除）
        var mainRoute = MakeMainRoute(1, StA, StC);
        var seg = MakeSegment(1, StA, StC);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StB, ToStationId = StC, StationConnectionId = sc.Id });
        train.StopTimesInternal[new StopKey(StA, 0)] = new StopTime();
        train.StopTimesInternal[new StopKey(StB, 0)] = new StopTime
        {
            Works = [new StationWork { Type = StationWorkType.Shunting }],
        };
        train.StopTimesInternal[new StopKey(StC, 0)] = new StopTime();

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg], session);
        command.Execute();

        Assert.DoesNotContain(new StopKey(StB, 0), train.StopTimes.Keys);
        Assert.Contains(new StopKey(StA, 0), train.StopTimes.Keys);
        Assert.Contains(new StopKey(StC, 0), train.StopTimes.Keys);
    }

    [Fact]
    public void 残存するStopKeyのStopTimeは既存の内容を引き継ぐ()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        var existingStopTime = new StopTime { ArrivalSeconds = 12345 };
        train.StopTimesInternal[new StopKey(StA, 0)] = existingStopTime;

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg], session);
        command.Execute();

        Assert.Same(existingStopTime, train.StopTimesInternal[new StopKey(StA, 0)]);
    }

    // -----------------------------
    // IsOverriddenFromTemplateの引き継ぎ
    // -----------------------------

    [Fact]
    public void IsOverriddenFromTemplateがtrueのホップは個別選択したStationConnectionが引き継がれる()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var defaultSc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var overriddenSc = MakeConnection(2, 1, StationConnectionDirection.Down, seg.Id); // 個別選択された別線
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, defaultSc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = StA,
            ToStationId = StB,
            StationConnectionId = overriddenSc.Id,
            IsOverriddenFromTemplate = true,
        });

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [defaultSc, overriddenSc], [seg], session);
        command.Execute();

        Assert.Equal(overriddenSc.Id, train.RunSegments[0].StationConnectionId);
        Assert.True(train.RunSegments[0].IsOverriddenFromTemplate);
    }

    [Fact]
    public void IsOverriddenFromTemplateがfalseのホップはデフォルトのStationConnectionへ置き換わる()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var defaultSc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var staleSc = MakeConnection(2, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, defaultSc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = StA,
            ToStationId = StB,
            StationConnectionId = staleSc.Id,
            IsOverriddenFromTemplate = false,
        });

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [defaultSc, staleSc], [seg], session);
        command.Execute();

        Assert.Equal(defaultSc.Id, train.RunSegments[0].StationConnectionId);
    }

    // -----------------------------
    // StationConnection候補解決
    // -----------------------------

    [Fact]
    public void SelectedStationConnectionId未設定でも候補が1件なら自動選択される()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, selected: null));

        var train = MakeValidTrain(1);

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg], session);
        command.Execute();

        Assert.Equal(sc.Id, train.RunSegments[0].StationConnectionId);
    }

    [Fact]
    public void SelectedStationConnectionId未設定で候補0件ならCreateが例外を送出する()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, selected: null));

        var train = MakeValidTrain(1);
        var session = MakeSession();

        Assert.Throws<InvalidOperationException>(() =>
            SyncRunSegmentsToTrainCommand.Create(train, serviceRoute, [mainRoute], [], [], session));
    }

    [Fact]
    public void SelectedStationConnectionId未設定で候補複数件ならCreateが例外を送出する()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var scX = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var scY = MakeConnection(2, 1, StationConnectionDirection.Down, seg.Id); // 複々線：候補2件
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, selected: null));

        var train = MakeValidTrain(1);
        var session = MakeSession();

        Assert.Throws<InvalidOperationException>(() =>
            SyncRunSegmentsToTrainCommand.Create(train, serviceRoute, [mainRoute], [scX, scY], [seg], session));
    }

    // -----------------------------
    // Undo
    // -----------------------------

    [Fact]
    public void UndoでRunSegmentsとStopTimesが元の状態に戻る()
    {
        var mainRoute = MakeMainRoute(1, StA, StB, StC);
        var seg1 = MakeSegment(1, StA, StB);
        var seg2 = MakeSegment(2, StB, StC);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg1.Id, seg2.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 2, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        var originalStopTime = new StopTime();
        train.StopTimesInternal[new StopKey(StB, 0)] = originalStopTime; // Syncで孤立・破棄される想定のキー

        var session = MakeSession();
        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg1, seg2], session);
        command.Execute();

        Assert.Equal(2, train.RunSegments.Count); // A-B, B-C に増える

        command.Undo();

        Assert.Single(train.RunSegments);
        Assert.Same(originalStopTime, train.StopTimesInternal[new StopKey(StB, 0)]);
    }

    // -----------------------------
    // AffectedIds
    // -----------------------------

    [Fact]
    public void AffectedIdsに自TrainのTrainObjectIdが含まれる()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, sc.Id));

        var train = MakeValidTrain(1);
        var session = MakeSession();

        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg], session);

        Assert.Contains(new TrainObjectId(train.Id), command.AffectedIds);
    }

    [Fact]
    public void 孤立したStopKeyを外部参照しているTrainがAffectedIdsに含まれる()
    {
        var mainRoute = MakeMainRoute(1, StA, StC); // Bが削除された新StationOrder
        var seg = MakeSegment(1, StA, StC);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StB, ToStationId = StC, StationConnectionId = sc.Id });
        var orphanedKey = new StopKey(StB, 0);
        train.StopTimesInternal[orphanedKey] = new StopTime();

        // StopKeyReferenceIndexBuilderはreferrerTrain側のStopTime.Worksを走査してIndexを構築するため、
        // cacheへ直接書き込む代わりにreferrer役のTrainをPrevTrain/SplitOrigin付きで正しく組み立てる。
        var referrerTrainId = new TrainId(99);
        var referrerTrain = MakeValidTrain(99, "9999M");
        referrerTrain.StopTimesInternal[new StopKey(StD, 0)] = new StopTime
        {
            Works =
            [
                new StationWork
                {
                    Type = StationWorkType.PrevTrain,
                    SplitOrigin = new SplitOriginRef { OriginTrainId = train.Id, OriginStopKey = orphanedKey },
                }
            ],
        };

        var session = MakeSession(referrerTrain);

        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg], session);

        Assert.Contains(new TrainObjectId(referrerTrainId), command.AffectedIds);
    }

    [Fact]
    public void 残存するStopKeyへの外部参照はAffectedIdsに影響しない()
    {
        var mainRoute = MakeMainRoute(1, StA, StB);
        var seg = MakeSegment(1, StA, StB);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);
        var serviceRoute = MakeServiceRoute(1, MakeSrSegment(1, 0, 1, sc.Id));

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = StA, ToStationId = StB, StationConnectionId = sc.Id });
        var survivingKey = new StopKey(StA, 0); // Syncしても消えないキー
        train.StopTimesInternal[survivingKey] = new StopTime();

        // 残存キーへのCouplingPartner参照はAffectedIdsに影響しないことを確認する。
        // （孤立キーではないため、そもそもorphanedKeysに含まれずBuildAffectedIdsのループを通らない）
        var unrelatedReferrerId = new TrainId(99);
        var unrelatedReferrerTrain = MakeValidTrain(99, "9999M");
        unrelatedReferrerTrain.StopTimesInternal[new StopKey(StD, 0)] = new StopTime
        {
            Works =
            [
                new StationWork
                {
                    Type = StationWorkType.Coupling,
                    CouplingDetail = new CouplingWork { PartnerTrainId = train.Id, PartnerStopKey = survivingKey },
                }
            ],
        };

        var session = MakeSession(unrelatedReferrerTrain);

        var command = SyncRunSegmentsToTrainCommand.Create(
            train, serviceRoute, [mainRoute], [sc], [seg], session);

        Assert.DoesNotContain(new TrainObjectId(unrelatedReferrerId), command.AffectedIds);
    }
}