using DiaEditCore.Model;
using DiaEditCore.Model.Routes;
using DiaEditCore.Model.Stations;
using DiaEditCore.Serialization.Validation;
using DiaEditCore.Serialization.Validation.Routes;
using Xunit;

namespace DiaEditCore.Tests.Serialization.Validation.Routes;
public class ServiceRouteValidatorTests
{
    [Fact]
    public void FromIndexとToIndexが同一だと不合格()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName { Name = "テスト系統" },
            IsAutoGenerated = false,
            Segments = [new ServiceRouteSegment { MainRouteId = new MainRouteId(1), FromStationIndex = 0, ToStationIndex = 0 }],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("同一"));
    }

    [Fact]
    public void IsUnidirectionalFalseでPairedフィールドが設定されていると不合格()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName { Name = "テスト系統" },
            IsAutoGenerated = false,
            Segments =
            [
                new ServiceRouteSegment
                {
                    MainRouteId = new MainRouteId(1),
                    FromStationIndex = 0,
                    ToStationIndex = 1,
                    IsUnidirectional = false,
                    PairedMainRouteId = new MainRouteId(2),
                },
            ],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("Paired系フィールド"));
    }

    [Fact]
    public void 隣接Segmentの境界駅が不一致だと不合格()
    {
        var routeA = new MainRoute { Id = new MainRouteId(1), Name = new DisplayName { Name = "A線" }, StationOrder = [new StationId(1), new StationId(2)] };
        var routeB = new MainRoute { Id = new MainRouteId(2), Name = new DisplayName { Name = "B線" }, StationOrder = [new StationId(99), new StationId(3)] }; // 境界駅がA線末尾(2)と一致しない

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName { Name = "テスト系統" },
            IsAutoGenerated = false,
            Segments =
            [
                new ServiceRouteSegment { MainRouteId = routeA.Id, FromStationIndex = 0, ToStationIndex = 1 },
                new ServiceRouteSegment { MainRouteId = routeB.Id, FromStationIndex = 0, ToStationIndex = 1 },
            ],
        };
        var context = new ValidationContext { MainRoutes = [routeA, routeB] };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("境界駅が不一致"));
    }

    [Fact]
    public void 境界駅が一致していれば合格()
    {
        var routeA = new MainRoute { Id = new MainRouteId(1), Name = new DisplayName { Name = "A線" }, StationOrder = [new StationId(1), new StationId(2)] };
        var routeB = new MainRoute { Id = new MainRouteId(2), Name = new DisplayName { Name = "B線" }, StationOrder = [new StationId(2), new StationId(3)] };

        var scA = new StationConnection { Id = new StationConnectionId(1), Name = "A下り", MainRouteId = routeA.Id, Direction = StationConnectionDirection.Down, Segments = [] };
        var scAUp = new StationConnection { Id = new StationConnectionId(2), Name = "A上り", MainRouteId = routeA.Id, Direction = StationConnectionDirection.Up, Segments = [] };
        var scB = new StationConnection { Id = new StationConnectionId(3), Name = "B下り", MainRouteId = routeB.Id, Direction = StationConnectionDirection.Down, Segments = [] };
        var scBUp = new StationConnection { Id = new StationConnectionId(4), Name = "B上り", MainRouteId = routeB.Id, Direction = StationConnectionDirection.Up, Segments = [] };

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName { Name = "テスト系統" },
            IsAutoGenerated = false,
            Segments =
            [
                new ServiceRouteSegment { MainRouteId = routeA.Id, FromStationIndex = 0, ToStationIndex = 1 },
                new ServiceRouteSegment { MainRouteId = routeB.Id, FromStationIndex = 0, ToStationIndex = 1 },
            ],
        };
        var context = new ValidationContext { MainRoutes = [routeA, routeB], StationConnections = [scA, scAUp, scB, scBUp] };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Empty(issues);
    }
}
public class ServiceRouteValidatorRule5Tests
{
    private static Rail TrackRail(int id, RailEndpointRef a, RailEndpointRef b) => new()
    {
        Id = new RailId(id), LengthM = 100, SpeedLimitKph = 60, Role = RailRole.Track,
        EndpointA = a, EndpointB = b,
    };

    private static StationPath Path(int id, StationPathDirection dir, params StationPathWaypoint[] wps) => new()
    {
        Id = new StationPathId(id), FloorUnitId = new FloorUnitId(1), Name = $"path{id}",
        Direction = dir, Waypoints = wps.ToList(),
    };

    private static MainRoute MakeRoute(MainRouteId id, bool isLoop, params StationId[] stations) => new()
    {
        Id = id, Name = new DisplayName { Name = "route" }, StationOrder = stations.ToList(), IsLoop = isLoop,
    };

    /// <summary>単一MainRoute（A-B-C）でSegmentsが1本のServiceRoute。境界駅チェックが正しく動作する
    /// 最小構成（B駅で到着線・出発線が同一Trackに接続）。</summary>
    private static (
        ServiceRoute sr, MainRoute route, StationConnection sc, List<StationConnectionSegment> segs,
        List<StationPath> paths, List<Rail> rails
    ) BuildSingleSegmentConnectedTopology()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var epA = new EntryPointId(1);
        var epBArr = new EntryPointId(2);
        var epBDep = new EntryPointId(3);
        var epC = new EntryPointId(4);
        var bp = new BoundaryPointId(10);
        var mainRouteId = new MainRouteId(1);

        var seg0 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(1), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = epA, ToEntryPointId = epBArr, MainRouteId = mainRouteId,
        };
        var seg1 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(2), FromStationId = stB, ToStationId = stC,
            FromEntryPointId = epBDep, ToEntryPointId = epC, MainRouteId = mainRouteId,
        };
        var sc = new StationConnection
        {
            Id = new StationConnectionId(1), Name = "sc", MainRouteId = mainRouteId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg0.Id, seg1.Id },
        };
        var route = MakeRoute(mainRouteId, isLoop: false, stA, stB, stC);

        var trackB = TrackRail(1, new EntryPointEndpointRef(epBArr), new BoundaryPointEndpointRef(bp));
        var arrivalPath = Path(1, StationPathDirection.Arrival, new EntryPointWaypoint(epBArr), new BoundaryPointWaypoint(bp));
        var departurePath = Path(2, StationPathDirection.Departure, new BoundaryPointWaypoint(bp), new EntryPointWaypoint(epBDep));

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 2 },
            },
        };

        return (sr, route, sc, new List<StationConnectionSegment> { seg0, seg1 },
            new List<StationPath> { arrivalPath, departurePath }, new List<Rail> { trackB });
    }

    private static ValidationContext MakeContext(
        MainRoute route, IEnumerable<StationConnection> scs, List<StationConnectionSegment> segs,
        List<StationPath> paths, List<Rail> rails) => new()
    {
        MainRoutes = new[] { route },
        StationConnections = scs.ToList(),
        StationConnectionSegments = segs,
        StationPaths = paths,
        Rails = rails,
    };

    // -----------------------------
    // ルール5：境界駅の整合性条件（単一MainRoute内、候補1件で自動選択されるケース）
    // -----------------------------

    [Fact]
    public void ルール5_単一Segmentで境界のTrack集合が重複するなら整合性エラーは出ない()
    {
        var (sr, route, sc, segs, paths, rails) = BuildSingleSegmentConnectedTopology();
        var context = MakeContext(route, new[] { sc }, segs, paths, rails);

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("境界駅の整合性条件"));
    }

    [Fact]
    public void ルール5_Track集合が重複しないとエラーになる()
    {
        var (sr, route, sc, segs, _, _) = BuildSingleSegmentConnectedTopology();
        var context = MakeContext(route, new[] { sc }, segs, new List<StationPath>(), new List<Rail>());

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("境界駅の整合性条件"));
    }

    [Fact]
    public void ルール5_ServiceRoute全体がループ_始発終着駅が同一なら先頭末尾境界も検証される()
    {
        var (sr, route, sc, segs, paths, rails) = BuildSingleSegmentConnectedTopology();
        // A→B→C→A の周回とみなせるよう、Segmentを2本にしてC→Aで閉じる
        var stA = route.StationOrder[0];
        var stC = route.StationOrder[2];
        var epCLoop = new EntryPointId(5);
        var epALoop = new EntryPointId(6);
        var seg2 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(3), FromStationId = stC, ToStationId = stA,
            FromEntryPointId = epCLoop, ToEntryPointId = epALoop, MainRouteId = route.Id,
        };
        var loopRoute = MakeRoute(route.Id, isLoop: false, stA, route.StationOrder[1], stC); // ServiceRoute側はMainRoute.IsLoopを見ないため任意
        var scWithLoop = new StationConnection
        {
            Id = sc.Id, Name = sc.Name, MainRouteId = route.Id, Direction = StationConnectionDirection.Down,
            Segments = new List<StationConnectionSegmentId> { segs[0].Id, segs[1].Id, seg2.Id },
        };
        var srLoop = new ServiceRoute
        {
            Id = sr.Id, Name = sr.Name, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = route.Id, FromStationIndex = 0, ToStationIndex = 0 }, // 実質使わないダミー、下記で置換
            },
        };
    }
        // -----------------------------
    // ループ判定（2つのMainRouteをA→B、B→Aと跨いで一周する構成）
    // -----------------------------

    [Fact]
    public void ルール5_2MainRouteでA発A着のループ構成なら先頭末尾境界も検証対象になる()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRouteAId = new MainRouteId(1);
        var mainRouteBId = new MainRouteId(2);

        // MainRouteA: A(0)→B(1)。B駅で出発線・到着線が同一Trackに接続する構成にする。
        var epA1 = new EntryPointId(1);       // A駅側出発（MainRouteA始点）
        var epB1Arr = new EntryPointId(2);    // B駅側到着（MainRouteA終点）
        var seg1 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(1), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = epA1, ToEntryPointId = epB1Arr, MainRouteId = mainRouteAId,
        };
        var scA = new StationConnection
        {
            Id = new StationConnectionId(1), Name = "scA", MainRouteId = mainRouteAId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg1.Id },
        };
        var routeA = MakeRoute(mainRouteAId, isLoop: false, stA, stB);

        // MainRouteB: B(0)→A(1)。B駅側出発EPをMainRouteAの到着EPと同一Trackに接続、
        // A駅側到着EPをMainRouteAの出発EPと同一Trackに接続することで、両方の境界を連結させる。
        var epB2Dep = new EntryPointId(3);    // B駅側出発（MainRouteB始点）
        var epA2Arr = new EntryPointId(4);    // A駅側到着（MainRouteB終点、ループを閉じる）
        var seg2 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(2), FromStationId = stB, ToStationId = stA,
            FromEntryPointId = epB2Dep, ToEntryPointId = epA2Arr, MainRouteId = mainRouteBId,
        };
        var scB = new StationConnection
        {
            Id = new StationConnectionId(2), Name = "scB", MainRouteId = mainRouteBId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg2.Id },
        };
        var routeB = MakeRoute(mainRouteBId, isLoop: false, stB, stA);

        // B駅境界：MainRouteAの到着EP(epB1Arr)とMainRouteBの出発EP(epB2Dep)が同一Trackに接続
        var bpB = new BoundaryPointId(10);
        var trackB = TrackRail(1, new EntryPointEndpointRef(epB1Arr), new BoundaryPointEndpointRef(bpB));
        var arrivalAtB = Path(1, StationPathDirection.Arrival, new EntryPointWaypoint(epB1Arr), new BoundaryPointWaypoint(bpB));
        var departureAtB = Path(2, StationPathDirection.Departure, new BoundaryPointWaypoint(bpB), new EntryPointWaypoint(epB2Dep));

        // A駅ループ境界：MainRouteBの到着EP(epA2Arr)とMainRouteAの出発EP(epA1)が同一Trackに接続（成立ケース）
        var bpA = new BoundaryPointId(11);
        var trackA = TrackRail(2, new EntryPointEndpointRef(epA2Arr), new BoundaryPointEndpointRef(bpA));
        var arrivalAtA = Path(3, StationPathDirection.Arrival, new EntryPointWaypoint(epA2Arr), new BoundaryPointWaypoint(bpA));
        var departureAtA = Path(4, StationPathDirection.Departure, new BoundaryPointWaypoint(bpA), new EntryPointWaypoint(epA1));

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "loop-sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteAId, FromStationIndex = 0, ToStationIndex = 1 }, // A→B
                new() { MainRouteId = mainRouteBId, FromStationIndex = 0, ToStationIndex = 1 }, // B→A
            },
        };

        var context = new ValidationContext
        {
            MainRoutes = new[] { routeA, routeB },
            StationConnections = new[] { scA, scB },
            StationConnectionSegments = new List<StationConnectionSegment> { seg1, seg2 },
            StationPaths = new List<StationPath> { arrivalAtB, departureAtB, arrivalAtA, departureAtA },
            Rails = new List<Rail> { trackB, trackA },
        };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        // B駅境界(Segment内部境界)・Aループ境界(先頭末尾境界)とも整合するため、境界駅整合性エラーは出ない
        Assert.DoesNotContain(issues, i => i.Message.Contains("境界駅の整合性条件"));
    }

    [Fact]
    public void ルール5_ループ構成でA駅側のループ境界のみ不整合ならエラーになる()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRouteAId = new MainRouteId(1);
        var mainRouteBId = new MainRouteId(2);

        var epA1 = new EntryPointId(1);
        var epB1Arr = new EntryPointId(2);
        var seg1 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(1), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = epA1, ToEntryPointId = epB1Arr, MainRouteId = mainRouteAId,
        };
        var scA = new StationConnection
        {
            Id = new StationConnectionId(1), Name = "scA", MainRouteId = mainRouteAId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg1.Id },
        };
        var routeA = MakeRoute(mainRouteAId, isLoop: false, stA, stB);

        var epB2Dep = new EntryPointId(3);
        var epA2Arr = new EntryPointId(4);
        var seg2 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(2), FromStationId = stB, ToStationId = stA,
            FromEntryPointId = epB2Dep, ToEntryPointId = epA2Arr, MainRouteId = mainRouteBId,
        };
        var scB = new StationConnection
        {
            Id = new StationConnectionId(2), Name = "scB", MainRouteId = mainRouteBId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg2.Id },
        };
        var routeB = MakeRoute(mainRouteBId, isLoop: false, stB, stA);

        // B駅境界のみ接続、A駅ループ境界は接続なし（StationPath/Railを与えない）
        var bpB = new BoundaryPointId(10);
        var trackB = TrackRail(1, new EntryPointEndpointRef(epB1Arr), new BoundaryPointEndpointRef(bpB));
        var arrivalAtB = Path(1, StationPathDirection.Arrival, new EntryPointWaypoint(epB1Arr), new BoundaryPointWaypoint(bpB));
        var departureAtB = Path(2, StationPathDirection.Departure, new BoundaryPointWaypoint(bpB), new EntryPointWaypoint(epB2Dep));

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "loop-sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteAId, FromStationIndex = 0, ToStationIndex = 1 },
                new() { MainRouteId = mainRouteBId, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var context = new ValidationContext
        {
            MainRoutes = new[] { routeA, routeB },
            StationConnections = new[] { scA, scB },
            StationConnectionSegments = new List<StationConnectionSegment> { seg1, seg2 },
            StationPaths = new List<StationPath> { arrivalAtB, departureAtB },
            Rails = new List<Rail> { trackB },
        };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("境界駅の整合性条件"));
    }
    // -----------------------------
    // ルール6：StationConnection候補が複数の場合の選択必須化
    // -----------------------------

    /// <summary>同一MainRouteId・同一Directionに2本のStationConnection（本線・緩行線）が存在する
    /// 複々線構成。両方とも同じA→B間で、それぞれ別Trackに接続する到着/出発StationPathを持つ。</summary>
    private static (
        MainRoute route, StationConnection scMain, StationConnection scLocal,
        List<StationConnectionSegment> segs, List<StationPath> paths, List<Rail> rails
    ) BuildDoubleTrackCandidateTopology()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRouteId = new MainRouteId(1);

        var epAMain = new EntryPointId(1);
        var epBMain = new EntryPointId(2);
        var segMain = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(1), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = epAMain, ToEntryPointId = epBMain, MainRouteId = mainRouteId,
        };
        var scMain = new StationConnection
        {
            Id = new StationConnectionId(1), Name = "本線", MainRouteId = mainRouteId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { segMain.Id },
        };

        var epALocal = new EntryPointId(3);
        var epBLocal = new EntryPointId(4);
        var segLocal = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(2), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = epALocal, ToEntryPointId = epBLocal, MainRouteId = mainRouteId,
        };
        var scLocal = new StationConnection
        {
            Id = new StationConnectionId(2), Name = "緩行線", MainRouteId = mainRouteId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { segLocal.Id },
        };

        var route = MakeRoute(mainRouteId, isLoop: false, stA, stB);

        // 単一Segment(N=1)構成なので境界チェック自体は発生しない（isLoop=falseかつ内部境界なし）。
        // ここではルール6の候補選択検証だけを見たいため、StationPath/Railは空でよい。
        return (route, scMain, scLocal, new List<StationConnectionSegment> { segMain, segLocal },
            new List<StationPath>(), new List<Rail>());
    }

    [Fact]
    public void ルール6_候補が複数でSelectedStationConnectionId未設定ならエラーになる()
    {
        var (route, scMain, scLocal, segs, paths, rails) = BuildDoubleTrackCandidateTopology();
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = route.Id, FromStationIndex = 0, ToStationIndex = 1 }, // SelectedStationConnectionId未設定
            },
        };
        var context = MakeContext(route, new[] { scMain, scLocal }, segs, paths, rails);

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("選択指定が必須"));
    }

    [Fact]
    public void ルール6_候補が複数でもSelectedStationConnectionId設定済みならエラーにならない()
    {
        var (route, scMain, scLocal, segs, paths, rails) = BuildDoubleTrackCandidateTopology();
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = route.Id, FromStationIndex = 0, ToStationIndex = 1, SelectedStationConnectionId = scLocal.Id },
            },
        };
        var context = MakeContext(route, new[] { scMain, scLocal }, segs, paths, rails);

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("選択指定が必須"));
        Assert.DoesNotContain(issues, i => i.Message.Contains("候補集合に含まれない"));
    }

    [Fact]
    public void ルール6_SelectedStationConnectionIdが候補集合に存在しないIdならエラーになる()
    {
        var (route, scMain, scLocal, segs, paths, rails) = BuildDoubleTrackCandidateTopology();
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = route.Id, FromStationIndex = 0, ToStationIndex = 1, SelectedStationConnectionId = new StationConnectionId(999) },
            },
        };
        var context = MakeContext(route, new[] { scMain, scLocal }, segs, paths, rails);

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("候補集合に含まれない"));
    }

    [Fact]
    public void ルール6_候補が1件のみならSelectedStationConnectionId未設定でもエラーにならない()
    {
        var (sr, route, sc, segs, paths, rails) = BuildSingleSegmentConnectedTopology();
        var context = MakeContext(route, new[] { sc }, segs, paths, rails);

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("選択指定が必須"));
    }

    // -----------------------------
    // Paired側の独立検証
    // -----------------------------

    /// <summary>mainRouteId側・pairedMainRouteId側それぞれ独立したA-B間の1区間構成。
    /// mainRouteId側は境界整合、pairedMainRouteId側は不整合（StationPath/Railなし）にする。</summary>
    private static (
        ServiceRoute sr, MainRoute mainRoute, MainRoute pairedRoute,
        StationConnection mainSc, StationConnection pairedSc,
        List<StationConnectionSegment> segs, List<StationPath> paths, List<Rail> rails
    ) BuildPairedTopology(bool pairedSideConnected)
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stP = new StationId(3);
        var stQ = new StationId(4);
        var mainRouteId = new MainRouteId(1);
        var pairedRouteId = new MainRouteId(2);

        var epA = new EntryPointId(1);
        var epB = new EntryPointId(2);
        var segMain = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(1), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = epA, ToEntryPointId = epB, MainRouteId = mainRouteId,
        };
        var mainSc = new StationConnection
        {
            Id = new StationConnectionId(1), Name = "main", MainRouteId = mainRouteId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { segMain.Id },
        };
        var mainRoute = MakeRoute(mainRouteId, isLoop: false, stA, stB);

        var epP = new EntryPointId(3);
        var epQ = new EntryPointId(4);
        var segPaired = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(2), FromStationId = stP, ToStationId = stQ,
            FromEntryPointId = epP, ToEntryPointId = epQ, MainRouteId = pairedRouteId,
        };
        var pairedSc = new StationConnection
        {
            Id = new StationConnectionId(2), Name = "paired", MainRouteId = pairedRouteId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { segPaired.Id },
        };
        var pairedRoute = MakeRoute(pairedRouteId, isLoop: false, stP, stQ);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "paired-sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new()
                {
                    MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 1,
                    IsUnidirectional = true,
                    PairedMainRouteId = pairedRouteId, PairedFromStationIndex = 0, PairedToStationIndex = 1,
                },
            },
        };

        // 単一Segment(N=1)構成のため、mainRouteId側・pairedMainRouteId側とも内部境界チェックは
        // 発生しない（isLoop判定用のStationOrder先頭末尾一致もここでは成立しない想定）。
        // Paired側の「独立して検証される」ことを確認する目的なので、あえて境界自体が
        // 発生しない単一区間構成のまま、StationPath/Rails自体を空にしてisLoop非該当を保つ。
        var paths = new List<StationPath>();
        var rails = new List<Rail>();

        return (sr, mainRoute, pairedRoute, mainSc, pairedSc,
            new List<StationConnectionSegment> { segMain, segPaired }, paths, rails);
    }

    [Fact]
    public void Paired側_全SegmentがPairedならPaired側も独立して検証される()
    {
        // 複々線構成にしてPaired側だけ候補選択エラーを起こし、Paired側が独立検証されることを確認する
        var (sr, mainRoute, pairedRoute, mainSc, pairedSc, segs, paths, rails) = BuildPairedTopology(pairedSideConnected: false);

        // pairedMainRouteId側にもう1本StationConnectionを追加して候補を複数にする
        var pairedRouteId = pairedRoute.Id;
        var stP = pairedRoute.StationOrder[0];
        var stQ = pairedRoute.StationOrder[1];
        var epP2 = new EntryPointId(5);
        var epQ2 = new EntryPointId(6);
        var segPaired2 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(3), FromStationId = stP, ToStationId = stQ,
            FromEntryPointId = epP2, ToEntryPointId = epQ2, MainRouteId = pairedRouteId,
        };
        var pairedSc2 = new StationConnection
        {
            Id = new StationConnectionId(3), Name = "paired2", MainRouteId = pairedRouteId,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { segPaired2.Id },
        };

        var context = new ValidationContext
        {
            MainRoutes = new[] { mainRoute, pairedRoute },
            StationConnections = new[] { mainSc, pairedSc, pairedSc2 },
            StationConnectionSegments = segs.Append(segPaired2).ToList(),
            StationPaths = paths,
            Rails = rails,
        };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        // mainRouteId側は候補1件のため自動選択されエラーなし。pairedMainRouteId側は候補2件かつ
        // PairedSelectedStationConnectionId未設定のため「Paired方向」のエラーが出るはず
        Assert.Contains(issues, i => i.Message.Contains("Paired方向") && i.Message.Contains("選択指定が必須"));
        Assert.DoesNotContain(issues, i => i.Message.Contains("主方向") && i.Message.Contains("選択指定が必須"));
    }

    [Fact]
    public void Paired側_一部SegmentのみPairedならPaired側の検証自体が行われない()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRouteId1 = new MainRouteId(1);
        var mainRouteId2 = new MainRouteId(2);
        var pairedRouteId = new MainRouteId(3);

        var seg1 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(1), FromStationId = stA, ToStationId = stB,
            FromEntryPointId = new EntryPointId(1), ToEntryPointId = new EntryPointId(2),
            MainRouteId = mainRouteId1,
        };
        var sc1 = new StationConnection
        {
            Id = new StationConnectionId(1), Name = "sc1", MainRouteId = mainRouteId1,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg1.Id },
        };
        var route1 = MakeRoute(mainRouteId1, isLoop: false, stA, stB);

        var seg2 = new StationConnectionSegment
        {
            Id = new StationConnectionSegmentId(2), FromStationId = stB, ToStationId = stC,
            FromEntryPointId = new EntryPointId(3), ToEntryPointId = new EntryPointId(4),
            MainRouteId = mainRouteId2,
        };
        var sc2 = new StationConnection
        {
            Id = new StationConnectionId(2), Name = "sc2", MainRouteId = mainRouteId2,
            Direction = StationConnectionDirection.Down, Segments = new List<StationConnectionSegmentId> { seg2.Id },
        };
        var route2 = MakeRoute(mainRouteId2, isLoop: false, stB, stC);

        var route3 = MakeRoute(pairedRouteId, isLoop: false, new StationId(5), new StationId(6));

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "partial-paired-sr"}, IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new()
                {
                    MainRouteId = mainRouteId1, FromStationIndex = 0, ToStationIndex = 1,
                    IsUnidirectional = true, PairedMainRouteId = pairedRouteId,
                    PairedFromStationIndex = 0, PairedToStationIndex = 1,
                    // PairedSelectedStationConnectionId未設定でも、Paired側検証自体が
                    // スキップされるため候補が複数あってもエラーにならないはず
                },
                new() { MainRouteId = mainRouteId2, FromStationIndex = 0, ToStationIndex = 1 }, // Paired情報なし
            },
        };

        var context = new ValidationContext
        {
            MainRoutes = new[] { route1, route2, route3 },
            StationConnections = new[] { sc1, sc2 },
            StationConnectionSegments = new List<StationConnectionSegment> { seg1, seg2 },
            StationPaths = new List<StationPath>(),
            Rails = new List<Rail>(),
        };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("Paired方向"));
    }
}
public class ServiceRouteValidatorPairedMixingTests
{
    // §8.2項目5（旧6）：IsUnidirectional=trueのSegment群内でPaired設定済み／未設定の混在を禁止する

    private static ServiceRouteSegment UniSeg(int mainRouteId, bool paired) => new()
    {
        MainRouteId = new MainRouteId(mainRouteId),
        FromStationIndex = 0,
        ToStationIndex = 1,
        IsUnidirectional = true,
        PairedMainRouteId = paired ? new MainRouteId(mainRouteId + 100) : null,
        PairedFromStationIndex = paired ? 0 : null,
        PairedToStationIndex = paired ? 1 : null,
    };

    [Fact]
    public void 全SegmentがUnidirectionalかつ全てPaired設定済みなら混在エラーは出ない()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = [UniSeg(1, paired: true), UniSeg(2, paired: true)],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("Paired設定が一部のみ存在する"));
    }

    [Fact]
    public void 全SegmentがUnidirectionalかつ全てPaired未設定なら混在エラーは出ない()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = [UniSeg(1, paired: false), UniSeg(2, paired: false)],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("Paired設定が一部のみ存在する"));
    }

    [Fact]
    public void UnidirectionalSegmentでPaired設定が一部のみだと混在エラーになる()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = [UniSeg(1, paired: true), UniSeg(2, paired: false)],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("Paired設定が一部のみ存在する") && i.Message.Contains("1/2件"));
    }

    [Fact]
    public void NonUnidirectionalSegmentはPaired混在判定の母数に含まれない()
    {
        // seg1: Unidirectional=true・Paired未設定, seg2: Unidirectional=false（母数から除外されるべき）
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments =
            [
                UniSeg(1, paired: false),
                new ServiceRouteSegment { MainRouteId = new MainRouteId(2), FromStationIndex = 0, ToStationIndex = 1, IsUnidirectional = false },
            ],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        // UnidirectionalなSegmentが1件のみ（母数1）なので、mixing自体が原理的に発生しない
        Assert.DoesNotContain(issues, i => i.Message.Contains("Paired設定が一部のみ存在する"));
    }

    [Fact]
    public void UnidirectionalSegmentが1件のみなら常に混在エラーにならない()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1), Name = new DisplayName{ Name = "sr"}, IsAutoGenerated = false,
            Segments = [UniSeg(1, paired: true)],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("Paired設定が一部のみ存在する"));
    }
}