namespace DiaEditCore.Model.Routes;

/// <summary>
/// 運転系統を構成する路線の区間
/// </summary>
public sealed class ServiceRouteSegment
{
    /// <summary>
    /// 対象の路線の識別子
    /// </summary>
    public required MainRouteId MainRouteId { get; set; }
    /// <summary>
    /// 路線の区間の始点
    /// </summary>
    /// <remarks>
    /// IdではなくIndex参照
    /// </remarks>
    public required int FromStationIndex { get; set; }
    /// <summary>
    /// 路線の区間の終点
    /// </summary>
    /// <remarks>
    /// IdではなくIndex参照。<br/>
    /// FromStationIndexより小さな値も可能。<br/>
    /// （例：特急ソニックの運行区間<br/>
    /// [博多→小倉]：上り<br/>
    /// [小倉→大分]：下りであるが、<br/>
    /// 便宜上、[博多→大分]：下りとして扱っている。）
    /// </remarks>
    public required int ToStationIndex { get; set; }
    /// <summary>
    /// 片方向専用区間フラグ
    /// </summary>
    /// <remarks>
    /// 経由する路線が非対称であったり、片方向専用の連絡線を経由する運転系統を表現する。<br/>
    /// 対称な路線を設定する場合は、下りを基準にすること。
    /// </remarks>
    public bool IsUnidirectional { get; set; } = false;

    /// <summary>
    /// IsUnidirectional == true の場合に指定する、対となる路線の識別子
    /// </summary>
    public MainRouteId? PairedMainRouteId { get; set; }
    /// <summary>
    /// 対となる路線の区間の始点
    /// </summary>
    public int? PairedFromStationIndex { get; set; }
    /// <summary>
    /// 対となる路線の区間の終点
    /// </summary>
    public int? PairedToStationIndex { get; set; }

    /// <summary>
    /// 路線の区間の終点で次の路線に移る際にスイッチバックが発生するか
    /// </summary>
    public bool ReversesAtBoundary { get; set; } = false;

    /// <summary>
    /// 複々線等でStationConnection候補が複数存在する区間のみ必須（候補1件なら省略可、自動選択） 
    /// </summary>
    public StationConnectionId? SelectedStationConnectionId { get; set; }
    /// <summary>
    /// 対となる路線で、複々線等でStationConnection候補が複数存在する区間のみ必須（候補1件なら省略可、自動選択） 
    /// </summary>
    public StationConnectionId? PairedSelectedStationConnectionId { get; set; }
}

public static class ServiceRouteSegmentExtensions
{
    // 「Pairedは異なる路線を経由して同じ始終着駅を持つ運転系統を表現するための仕組み」という前提のため、
    // Paired系フィールドが全て設定済みの場合のみtrue（ServiceRoutePathResolver・ServiceRouteValidatorで共用）
    public static bool IsPaired(this ServiceRouteSegment segment)
        => segment.IsUnidirectional
           && segment.PairedMainRouteId.HasValue
           && segment.PairedFromStationIndex.HasValue
           && segment.PairedToStationIndex.HasValue;
}

/// <summary>
/// 運転系統を表す
/// </summary>
/// <remarks>
/// 福北ゆたか線（筑豊本線、篠栗線、鹿児島本線）やJR神戸線・JR京都線・JR琵琶湖線（東海道本線）など、愛称や直通系統を表現する。
/// </remarks>
public sealed class ServiceRoute
{
    /// <summary>
    /// 運転系統識別子
    /// </summary>
    public required ServiceRouteId Id { get; set; }
    /// <summary>
    /// 運転系統名
    /// </summary>
    public required DisplayName Name { get; set; }
    /// <summary>
    /// 自動生成フラグ
    /// </summary>
    /// <remarks>
    /// 1 MainRouteにつき 1 ServiceRouteが自動で生成される。これは削除不可。
    /// </remarks>
    public required bool IsAutoGenerated { get; set; }
    /// <summary>
    /// 運転系統を構成する路線と区間情報
    /// </summary>
    public required List<ServiceRouteSegment> Segments { get; set; }
}