namespace DiaEditCore.Model.Routes;

public sealed class ServiceRouteSegment
{
    public required MainRouteId MainRouteId { get; set; }
    public required int FromStationIndex { get; set; }
    public required int ToStationIndex { get; set; }
    public bool IsUnidirectional { get; set; } = false;

    public MainRouteId? PairedMainRouteId { get; set; }
    public int? PairedFromStationIndex { get; set; }
    public int? PairedToStationIndex { get; set; }

    public bool ReversesAtBoundary { get; set; } = false;

    // 複々線等でStationConnection候補が複数存在する区間のみ必須（候補1件なら省略可、自動選択）
    public StationConnectionId? SelectedStationConnectionId { get; set; }
    public StationConnectionId? PairedSelectedStationConnectionId { get; set; }
}

public static class ServiceRouteSegmentExtensions
{
    // 「Pairedは異なる路線を経由して同じ始終着駅を持つ運転系統を表現するための仕組み」という前提のため、
    // Paired系フィールドが全て設定済みの場合のみtrue（ServiceRoutePathResolver・ServiceRouteValidatorで共用）
    public static bool IsPaired(this ServiceRouteSegment segment)
        => segment.IsUnidirectional
           && segment.PairedMainRouteId.HasValue
           && segment.PairedFromStationIndex.HasValue
           && segment.PairedToStationIndex.HasValue;
}

public sealed class ServiceRoute
{
    public required ServiceRouteId Id { get; set; }
    public required DisplayName Name { get; set; }
    public required bool IsAutoGenerated { get; set; }
    public required List<ServiceRouteSegment> Segments { get; set; }
}