namespace DiaEditCore.Model.Routes;

public sealed class ServiceRouteSegment
{
    public required MainRouteId MainRouteId { get; set; }
    public required int FromStationIndex { get; set; } // MainRouteId.StationOrder上のインデックス
    public required int ToStationIndex { get; set; }
    public bool IsUnidirectional { get; set; } = false;

    // IsUnidirectional=trueの場合のみ使用
    public MainRouteId? PairedMainRouteId { get; set; }
    public int? PairedFromStationIndex { get; set; }
    public int? PairedToStationIndex { get; set; }

    public bool ReversesAtBoundary { get; set; } = false; // 現時点ではユーザー明示指定
}

public sealed class ServiceRoute
{
    public required ServiceRouteId Id { get; set; }
    public required string Name { get; set; }
    public required bool IsAutoGenerated { get; set; } // true = MainRoute作成時の自動生成、編集・削除不可
    public required List<ServiceRouteSegment> Segments { get; set; }
}