namespace DiaEditCore.Model;

public readonly record struct StationId(int Value);
public readonly record struct FloorUnitId(int Value);
public readonly record struct RailId(int Value);
public readonly record struct BoundaryPointId(int Value);
public readonly record struct EntryPointId(int Value);
public readonly record struct BufferStopId(int Value);
public readonly record struct SwitcherId(int Value);
public readonly record struct StationPathId(int Value);
public readonly record struct VirtualConflictObjectId(int Value);
public readonly record struct MainRouteId(int Value);
public readonly record struct StationConnectionSegmentId(int Value);
public readonly record struct StationConnectionId(int Value);
public readonly record struct ServiceRouteId(int Value);
public readonly record struct VehicleTypeId(int Value);
public readonly record struct AttachedCarTemplateId(int Value);
public readonly record struct CarConsistId(int Value);
public readonly record struct CarId(int Value);
public readonly record struct InsertionConfigId(int Value);
public readonly record struct TrainTypeId(int Value);
public readonly record struct TrainId(int Value);
public readonly record struct TrainOperationId(int Value);