namespace DiaEditCore.Tests.Algorithm;

using DiaEditCore.Algorithm;
using DiaEditCore.Model;
using DiaEditCore.Model.Routes;

using Xunit;

public class ServiceRoutePathResolverTests
{
    private static MainRoute MakeMainRoute(MainRouteId id, params StationId[] stations)
        => new()
        {
            Id = id,
            Name = new DisplayName { Name = "test-main-route" },
            StationOrder = stations.ToList(),
        };

    private static StationConnectionSegment MakeSegment(
        StationConnectionSegmentId id, StationId from, StationId to, MainRouteId mainRouteId)
        => new()
        {
            Id = id,
            StationIdA = from,
            StationIdB = to,
            EntryPointIdA = new EntryPointId(id.Value * 10 + 1),
            EntryPointIdB = new EntryPointId(id.Value * 10 + 2),
            MainRouteId = mainRouteId,
        };

    private static StationConnection MakeConnection(
        StationConnectionId id, MainRouteId mainRouteId, StationConnectionDirection direction,
        params StationConnectionSegmentId[] segmentIds)
        => new()
        {
            Id = id,
            Name = "test-sc",
            MainRouteId = mainRouteId,
            Direction = direction,
            Segments = segmentIds.ToList(),
        };

    private static readonly ServiceRoutePathResolver.CandidateSelector ThrowIfCalled =
        (_, _) => throw new InvalidOperationException("候補が1件のみのときはselectorが呼ばれないはず");

    // 単純な2駅1本線（A-B、Down方向のみ）を1区間だけのServiceRouteに使う共通フィクスチャ
    private static (MainRoute mainRoute, StationConnection connection, StationConnectionSegment segment)
        BuildSimpleTwoStationDown(MainRouteId mainRouteId, StationId stA, StationId stB, int idSeed)
    {
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB);
        var seg = MakeSegment(new StationConnectionSegmentId(idSeed), stA, stB, mainRouteId);
        var sc = MakeConnection(new StationConnectionId(idSeed), mainRouteId, StationConnectionDirection.Down, seg.Id);
        return (mainRoute, sc, seg);
    }

    [Fact]
    public void 正常系_非paired単一segmentならprimarySeqのみ1本返る()
    {
        var mainRouteId = new MainRouteId(1);
        var (mainRoute, sc, seg) = BuildSimpleTwoStationDown(mainRouteId, new StationId(1), new StationId(2), 1);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr, new List<MainRoute> { mainRoute }, new List<StationConnection> { sc },
            new List<StationConnectionSegment> { seg }, ThrowIfCalled);

        Assert.Single(result); // primarySeqのみ
        Assert.Single(result[0]);
        Assert.NotNull(result[0][0]);
        Assert.Equal(new StationId(1), result[0][0]!.FromStationId);
        Assert.Equal(new StationId(2), result[0][0]!.ToStationId);
    }

    [Fact]
    public void 正常系_全segmentがpairedならprimarySeqとpairedSeqの2本返る()
    {
        var mainRouteId = new MainRouteId(1);
        var pairedMainRouteId = new MainRouteId(2);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var stD = new StationId(4);

        var (mainRoute, sc, seg) = BuildSimpleTwoStationDown(mainRouteId, stA, stB, 1);
        var (pairedMainRoute, pairedSc, pairedSeg) = BuildSimpleTwoStationDown(pairedMainRouteId, stC, stD, 2);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new()
                {
                    MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 1,
                    IsUnidirectional = true,
                    PairedMainRouteId = pairedMainRouteId,
                    PairedFromStationIndex = 0,
                    PairedToStationIndex = 1,
                },
            },
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr,
            new List<MainRoute> { mainRoute, pairedMainRoute },
            new List<StationConnection> { sc, pairedSc },
            new List<StationConnectionSegment> { seg, pairedSeg },
            ThrowIfCalled);

        Assert.Equal(2, result.Count);
        Assert.Equal(stA, result[0][0]!.FromStationId);
        Assert.Equal(stB, result[0][0]!.ToStationId);
        Assert.Equal(stC, result[1][0]!.FromStationId);
        Assert.Equal(stD, result[1][0]!.ToStationId);
    }

    [Fact]
    public void 正常系_一部segmentのみpairedの場合は全体が非paired扱いになりprimarySeqのみ返る()
    {
        var mainRouteId1 = new MainRouteId(1);
        var mainRouteId2 = new MainRouteId(2);
        var pairedMainRouteId = new MainRouteId(3);

        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var stP = new StationId(4);
        var stQ = new StationId(5);

        var (mainRoute1, sc1, seg1) = BuildSimpleTwoStationDown(mainRouteId1, stA, stB, 1);
        var (mainRoute2, sc2, seg2) = BuildSimpleTwoStationDown(mainRouteId2, stB, stC, 2);
        var (pairedMainRoute, pairedSc, pairedSeg) = BuildSimpleTwoStationDown(pairedMainRouteId, stP, stQ, 3);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                // 1つ目のsegmentはpaired情報あり
                new()
                {
                    MainRouteId = mainRouteId1, FromStationIndex = 0, ToStationIndex = 1,
                    IsUnidirectional = true,
                    PairedMainRouteId = pairedMainRouteId,
                    PairedFromStationIndex = 0,
                    PairedToStationIndex = 1,
                },
                // 2つ目のsegmentはpaired情報なし
                new() { MainRouteId = mainRouteId2, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr,
            new List<MainRoute> { mainRoute1, mainRoute2, pairedMainRoute },
            new List<StationConnection> { sc1, sc2, pairedSc },
            new List<StationConnectionSegment> { seg1, seg2, pairedSeg },
            ThrowIfCalled);

        Assert.Single(result); // pairedSeqは生成されない
        Assert.Equal(2, result[0].Count);
    }

    [Fact]
    public void 異常系_対応するStationConnectionが存在しない場合は該当要素がnullになる()
    {
        var mainRouteId = new MainRouteId(1);
        var mainRoute = MakeMainRoute(mainRouteId, new StationId(1), new StationId(2));

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr, new List<MainRoute> { mainRoute }, new List<StationConnection>(),
            new List<StationConnectionSegment>(), ThrowIfCalled);

        Assert.Single(result);
        Assert.Single(result[0]);
        Assert.Null(result[0][0]);
    }

    [Fact]
    public void 複々線_候補が複数ある場合はselectorが呼ばれその戻り値が採用される()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB);

        var segMain = MakeSegment(new StationConnectionSegmentId(1), stA, stB, mainRouteId);
        var segLocal = MakeSegment(new StationConnectionSegmentId(2), stA, stB, mainRouteId);
        var scMain = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Down, segMain.Id);
        var scLocal = MakeConnection(new StationConnectionId(2), mainRouteId, StationConnectionDirection.Down, segLocal.Id);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var selectorCalled = false;
        ServiceRoutePathResolver.CandidateSelector selector = (_, candidates) =>
        {
            selectorCalled = true;
            // 緩行線側（2件目の候補）を明示的に選ぶ
            return candidates[1];
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { scMain, scLocal },
            new List<StationConnectionSegment> { segMain, segLocal },
            selector);

        Assert.True(selectorCalled);
        Assert.Single(result);
        Assert.NotNull(result[0][0]);
    }

    [Fact]
    public void 正常系_複数segmentが連結される場合は境界駅で要素数がsegments数と一致する()
    {
        var mainRouteId1 = new MainRouteId(1);
        var mainRouteId2 = new MainRouteId(2);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var stD = new StationId(4);

        var (mainRoute1, sc1, seg1) = BuildSimpleTwoStationDown(mainRouteId1, stA, stB, 1);
        var (mainRoute2, sc2, seg2) = BuildSimpleTwoStationDown(mainRouteId2, stC, stD, 2);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId1, FromStationIndex = 0, ToStationIndex = 1 },
                new() { MainRouteId = mainRouteId2, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr,
            new List<MainRoute> { mainRoute1, mainRoute2 },
            new List<StationConnection> { sc1, sc2 },
            new List<StationConnectionSegment> { seg1, seg2 },
            ThrowIfCalled);

        Assert.Single(result);
        Assert.Equal(2, result[0].Count);
        Assert.Equal(stA, result[0][0]!.FromStationId);
        Assert.Equal(stB, result[0][0]!.ToStationId);
        Assert.Equal(stC, result[0][1]!.FromStationId);
        Assert.Equal(stD, result[0][1]!.ToStationId);
    }

    [Fact]
    public void 異常系_segmentsが空の場合はprimarySeqのみで空リストが返る()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>(),
        };

        var result = ServiceRoutePathResolver.ResolveServiceRoutePath(
            sr, new List<MainRoute>(), new List<StationConnection>(),
            new List<StationConnectionSegment>(), ThrowIfCalled);

        Assert.Single(result);
        Assert.Empty(result[0]);
    }
}
