using DiaEditCore.Algorithm;
using DiaEditCore.Model;
using DiaEditCore.Model.Routes;
using DiaEditCore.Model.Stations;
using DiaEditCore.Model.TimeTable.Trains;
using Xunit;

namespace DiaEditCore.Tests.Algorithm;

public class ServiceRouteToRunSegmentsResolverTests
{
    // -----------------------------
    // 共通フィクスチャヘルパー（BoundaryEntryPointResolverTests / MainRouteCheckerTestsの流儀に合わせる）
    // -----------------------------

    private static MainRoute MakeMainRoute(MainRouteId id, params StationId[] stations) => new()
    {
        Id = id,
        Name = new DisplayName { Name = "test-main-route" },
        StationOrder = stations.ToList(),
    };

    private static StationConnectionSegment MakeSegment(
        StationConnectionSegmentId id, StationId from, StationId to, MainRouteId mainRouteId,
        EntryPointId? fromEp = null, EntryPointId? toEp = null) => new()
    {
        Id = id,
        FromStationId = from,
        ToStationId = to,
        FromEntryPointId = fromEp ?? new EntryPointId(id.Value * 10 + 1),
        ToEntryPointId = toEp ?? new EntryPointId(id.Value * 10 + 2),
        MainRouteId = mainRouteId,
    };

    private static StationConnection MakeConnection(
        StationConnectionId id, MainRouteId mainRouteId, StationConnectionDirection direction,
        params StationConnectionSegmentId[] segmentIds) => new()
    {
        Id = id,
        Name = $"SC{id.Value}",
        MainRouteId = mainRouteId,
        Direction = direction,
        Segments = segmentIds.ToList(),
    };

    private static ServiceRoute MakeServiceRoute(params ServiceRouteSegment[] segments) => new()
    {
        Id = new ServiceRouteId(1),
        Name = new DisplayName { Name = "test-service-route" },
        IsAutoGenerated = false,
        Segments = segments.ToList(),
    };

    private static ServiceRouteSegment MakeSrSegment(MainRouteId mainRouteId, int fromIdx, int toIdx) => new()
    {
        MainRouteId = mainRouteId,
        FromStationIndex = fromIdx,
        ToStationIndex = toIdx,
    };

    private static Rail TrackRail(int id, RailEndpointRef a, RailEndpointRef b) => new()
    {
        Id = new RailId(id),
        LengthM = 100,
        SpeedLimitKph = 60,
        Role = RailRole.Track,
        EndpointA = a,
        EndpointB = b,
    };

    private static StationPath Path(int id, StationPathDirection dir, params StationPathWaypoint[] wps) => new()
    {
        Id = new StationPathId(id),
        FloorUnitId = new FloorUnitId(1),
        Name = $"path{id}",
        Direction = dir,
        Waypoints = wps.ToList(),
    };

    /// <summary>selectorが呼ばれないはずのテストで、呼ばれたら即座に失敗させる番人。</summary>
    private static ServiceRouteToRunSegmentsResolver.HopCandidateSelector NeverCalledSelector =>
        (_, _, _, _) => throw new InvalidOperationException("selectorが呼ばれるべきではない状況で呼ばれた");

    // -----------------------------
    // ① 候補1件は自動確定される（selectorは呼ばれない）
    // -----------------------------
    [Fact]
    public void 候補が1件のみのホップは自動確定しselectorは呼ばれない()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB);

        var seg = MakeSegment(new StationConnectionSegmentId(1), stA, stB, mainRouteId);
        var sc = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Down, seg.Id);

        var sr = MakeServiceRoute(MakeSrSegment(mainRouteId, 0, 1));

        var result = ServiceRouteToRunSegmentsResolver.Resolve(
            sr, isUpDirection: false,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { sc },
            new List<StationConnectionSegment> { seg },
            Array.Empty<StationPath>(), Array.Empty<Rail>(),
            NeverCalledSelector);

        var resolved = Assert.Single(result);
        var hop = Assert.IsType<HopResolved>(resolved);
        Assert.Equal(stA, hop.Segment.FromStationId);
        Assert.Equal(stB, hop.Segment.ToStationId);
        Assert.Equal(sc.Id, hop.Segment.StationConnectionId);
        Assert.False(hop.Segment.IsOverriddenFromTemplate);
    }

    // -----------------------------
    // ② 直前ホップのSCが候補集合に含まれる場合は継承する（selectorは呼ばれない）
    //    ＝広域SC（複数ホップをカバー）が一貫して選ばれ続けるケースを兼ねる
    // -----------------------------
    [Fact]
    public void 直前ホップのSCが候補に含まれる場合は継承しselectorは呼ばれない()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);

        var seg1 = MakeSegment(new StationConnectionSegmentId(1), stA, stB, mainRouteId);
        var seg2 = MakeSegment(new StationConnectionSegmentId(2), stB, stC, mainRouteId);

        // scWideは両ホップをカバーする広域SC。scNarrowはhop2のみをカバーする対抗候補。
        var scWide = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Down, seg1.Id, seg2.Id);
        var scNarrow = MakeConnection(new StationConnectionId(2), mainRouteId, StationConnectionDirection.Down, seg2.Id);

        var sr = MakeServiceRoute(MakeSrSegment(mainRouteId, 0, 2));

        var result = ServiceRouteToRunSegmentsResolver.Resolve(
            sr, isUpDirection: false,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { scWide, scNarrow },
            new List<StationConnectionSegment> { seg1, seg2 },
            Array.Empty<StationPath>(), Array.Empty<Rail>(),
            NeverCalledSelector);

        Assert.Equal(2, result.Count);

        var hop1 = Assert.IsType<HopResolved>(result[0]);
        Assert.Equal(scWide.Id, hop1.Segment.StationConnectionId); // hop1は候補1件で自動確定

        var hop2 = Assert.IsType<HopResolved>(result[1]);
        Assert.Equal(scWide.Id, hop2.Segment.StationConnectionId); // hop2は候補2件だがscWideを継承
    }

    // -----------------------------
    // ③ selectorが直前と異なるSCを選び、転線可能（Track集合重複）なら確定する
    // -----------------------------
    [Fact]
    public void selectorが直前と異なるSCを選び転線可能なら確定する()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);

        var epArr = new EntryPointId(12);  // scXの到着側EP（B駅）
        var epDep = new EntryPointId(31);  // scBの出発側EP（B駅）

        var seg1 = MakeSegment(new StationConnectionSegmentId(1), stA, stB, mainRouteId, toEp: epArr);
        var seg2A = MakeSegment(new StationConnectionSegmentId(2), stB, stC, mainRouteId);
        var seg2B = MakeSegment(new StationConnectionSegmentId(3), stB, stC, mainRouteId, fromEp: epDep);

        var scX = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Down, seg1.Id);
        var scA = MakeConnection(new StationConnectionId(2), mainRouteId, StationConnectionDirection.Down, seg2A.Id);
        var scB = MakeConnection(new StationConnectionId(3), mainRouteId, StationConnectionDirection.Down, seg2B.Id);

        // B駅で epArr(scX到着) と epDep(scB出発) が同一Trackに接続している＝転線可能なトポロジー
        var bp = new BoundaryPointId(10);
        var trackB = TrackRail(1, new EntryPointEndpointRef(epArr), new BoundaryPointEndpointRef(bp));
        var arrivalPath = Path(1, StationPathDirection.Arrival, new EntryPointWaypoint(epArr), new BoundaryPointWaypoint(bp));
        var departurePath = Path(2, StationPathDirection.Departure, new BoundaryPointWaypoint(bp), new EntryPointWaypoint(epDep));

        var sr = MakeServiceRoute(MakeSrSegment(mainRouteId, 0, 2));

        var result = ServiceRouteToRunSegmentsResolver.Resolve(
            sr, isUpDirection: false,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { scX, scA, scB },
            new List<StationConnectionSegment> { seg1, seg2A, seg2B },
            new List<StationPath> { arrivalPath, departurePath },
            new List<Rail> { trackB },
            (from, to, candidates, prev) =>
            {
                Assert.Equal(stB, from);
                Assert.Equal(stC, to);
                Assert.Equal(scX.Id, prev);
                Assert.Contains(scB.Id, candidates);
                return scB.Id; // 直前(scX)と異なるSCを選ぶ
            });

        Assert.Equal(2, result.Count);
        var hop2 = Assert.IsType<HopResolved>(result[1]);
        Assert.Equal(scB.Id, hop2.Segment.StationConnectionId);
    }

    // -----------------------------
    // ④ selectorが直前と異なるSCを選んだが転線不可（Track集合が重複しない）ならブロックされる
    // -----------------------------
    [Fact]
    public void selectorが直前と異なるSCを選び転線不可ならHopTransferBlockedになる()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);

        var epArr = new EntryPointId(12);  // scXの到着側EP（B駅）
        var epDep = new EntryPointId(31);  // scBの出発側EP（B駅、epArrとは別Trackに接続＝転線不可）

        var seg1 = MakeSegment(new StationConnectionSegmentId(1), stA, stB, mainRouteId, toEp: epArr);
        var seg2A = MakeSegment(new StationConnectionSegmentId(2), stB, stC, mainRouteId);
        var seg2B = MakeSegment(new StationConnectionSegmentId(3), stB, stC, mainRouteId, fromEp: epDep);

        var scX = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Down, seg1.Id);
        var scA = MakeConnection(new StationConnectionId(2), mainRouteId, StationConnectionDirection.Down, seg2A.Id);
        var scB = MakeConnection(new StationConnectionId(3), mainRouteId, StationConnectionDirection.Down, seg2B.Id);

        // epArrとepDepは別々のTrackに接続（重複なし＝転線不可）
        var arrivalTrack = TrackRail(1, new EntryPointEndpointRef(epArr), new BoundaryPointEndpointRef(new BoundaryPointId(10)));
        var departureTrack = TrackRail(2, new EntryPointEndpointRef(epDep), new BoundaryPointEndpointRef(new BoundaryPointId(11)));
        var arrivalPath = Path(1, StationPathDirection.Arrival, new EntryPointWaypoint(epArr), new BoundaryPointWaypoint(new BoundaryPointId(10)));
        var departurePath = Path(2, StationPathDirection.Departure, new BoundaryPointWaypoint(new BoundaryPointId(11)), new EntryPointWaypoint(epDep));

        var sr = MakeServiceRoute(MakeSrSegment(mainRouteId, 0, 2));

        var result = ServiceRouteToRunSegmentsResolver.Resolve(
            sr, isUpDirection: false,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { scX, scA, scB },
            new List<StationConnectionSegment> { seg1, seg2A, seg2B },
            new List<StationPath> { arrivalPath, departurePath },
            new List<Rail> { arrivalTrack, departureTrack },
            (from, to, candidates, prev) => scB.Id); // 直前(scX)と異なるSCを選ぶ

        Assert.Equal(2, result.Count);
        Assert.IsType<HopResolved>(result[0]);

        var blocked = Assert.IsType<HopTransferBlocked>(result[1]);
        Assert.Equal(stB, blocked.FromStationId);
        Assert.Equal(stC, blocked.ToStationId);
        Assert.Equal(scB.Id, blocked.AttemptedScId);
        Assert.Equal(scX.Id, blocked.PreviousScId);
    }

    // -----------------------------
    // ⑤ selectorがnullを返すとHopUnresolvedになり、継承の連鎖がリセットされる
    // -----------------------------
    [Fact]
    public void selectorがnullを返すとHopUnresolvedになり次ホップで継承がリセットされる()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var stD = new StationId(4);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC, stD);

        var seg1 = MakeSegment(new StationConnectionSegmentId(1), stA, stB, mainRouteId);
        var seg2A = MakeSegment(new StationConnectionSegmentId(2), stB, stC, mainRouteId);
        var seg2B = MakeSegment(new StationConnectionSegmentId(3), stB, stC, mainRouteId);
        var seg3A = MakeSegment(new StationConnectionSegmentId(4), stC, stD, mainRouteId);
        var seg3B = MakeSegment(new StationConnectionSegmentId(5), stC, stD, mainRouteId);

        var scX = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Down, seg1.Id);
        var scA = MakeConnection(new StationConnectionId(2), mainRouteId, StationConnectionDirection.Down, seg2A.Id);
        var scB = MakeConnection(new StationConnectionId(3), mainRouteId, StationConnectionDirection.Down, seg2B.Id);
        var scC = MakeConnection(new StationConnectionId(4), mainRouteId, StationConnectionDirection.Down, seg3A.Id);
        var scD = MakeConnection(new StationConnectionId(5), mainRouteId, StationConnectionDirection.Down, seg3B.Id);

        var sr = MakeServiceRoute(MakeSrSegment(mainRouteId, 0, 3));

        var callLog = new List<StationConnectionId?>();

        var result = ServiceRouteToRunSegmentsResolver.Resolve(
            sr, isUpDirection: false,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { scX, scA, scB, scC, scD },
            new List<StationConnectionSegment> { seg1, seg2A, seg2B, seg3A, seg3B },
            Array.Empty<StationPath>(), Array.Empty<Rail>(),
            (from, to, candidates, prev) =>
            {
                callLog.Add(prev);
                if (from == stB) return null;       // hop2：ユーザーが保留
                return scC.Id;                       // hop3：確定させる
            });

        Assert.Equal(3, result.Count);
        Assert.IsType<HopResolved>(result[0]);
        Assert.IsType<HopUnresolved>(result[1]);

        var hop3 = Assert.IsType<HopResolved>(result[2]);
        Assert.Equal(scC.Id, hop3.Segment.StationConnectionId);

        // hop2呼び出し時点のprevious=scX、hop3呼び出し時点ではリセットされてnullであること
        Assert.Equal(2, callLog.Count);
        Assert.Equal(scX.Id, callLog[0]);
        Assert.Null(callLog[1]);
    }

    // -----------------------------
    // ⑥ 上り方向はSegment列の順序反転＋各Segment内のFrom/ToStationIndex入れ替えで解決される
    // -----------------------------
    [Fact]
    public void 上り方向はSegment順序反転とインデックス入れ替えで解決される()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);

        // 上り方向用のSegmentは、既存のBoundaryEntryPointResolverの規約通り
        // From/Toが走行方向と一致する別エンティティとして用意する
        var segUp1 = MakeSegment(new StationConnectionSegmentId(1), stC, stB, mainRouteId); // C→B
        var segUp2 = MakeSegment(new StationConnectionSegmentId(2), stB, stA, mainRouteId); // B→A

        var scUp1 = MakeConnection(new StationConnectionId(1), mainRouteId, StationConnectionDirection.Up, segUp1.Id);
        var scUp2 = MakeConnection(new StationConnectionId(2), mainRouteId, StationConnectionDirection.Up, segUp2.Id);

        // ServiceRoute自体は下り基準（A(0)→C(2)）で定義されている
        var sr = MakeServiceRoute(MakeSrSegment(mainRouteId, 0, 2));

        var result = ServiceRouteToRunSegmentsResolver.Resolve(
            sr, isUpDirection: true,
            new List<MainRoute> { mainRoute },
            new List<StationConnection> { scUp1, scUp2 },
            new List<StationConnectionSegment> { segUp1, segUp2 },
            Array.Empty<StationPath>(), Array.Empty<Rail>(),
            NeverCalledSelector);

        Assert.Equal(2, result.Count);

        var hop1 = Assert.IsType<HopResolved>(result[0]);
        Assert.Equal(stC, hop1.Segment.FromStationId);
        Assert.Equal(stB, hop1.Segment.ToStationId);
        Assert.Equal(scUp1.Id, hop1.Segment.StationConnectionId);

        var hop2 = Assert.IsType<HopResolved>(result[1]);
        Assert.Equal(stB, hop2.Segment.FromStationId);
        Assert.Equal(stA, hop2.Segment.ToStationId);
        Assert.Equal(scUp2.Id, hop2.Segment.StationConnectionId);
    }
}