using DiaEditCore.Algorithm;

using DiaEditCore.Model;
using DiaEditCore.Model.Routes;

using Xunit;

namespace DiaEditCore.Tests.Algorithm;

public class ServiceRouteStationOrderResolverTests
{
    private static MainRoute MakeMainRoute(MainRouteId id, params StationId[] stations)
        => new()
        {
            Id = id,
            Name = new DisplayName { Name = "test-main-route" },
            StationOrder = stations.ToList(),
        };

    [Fact]
    public void 正常系_単一segmentで中間駅を含む全駅が順序通りに返る()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "test-sr",
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 2 },
            },
        };

        var result = ServiceRouteStationOrderResolver.ResolveServiceRouteStationOrder(
            sr, new List<MainRoute> { mainRoute });

        Assert.Equal(new[] { stA, stB, stC }, result);
    }

    [Fact]
    public void 正常系_降順segmentでは駅列が逆順になる()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "test-sr",
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 2, ToStationIndex = 0 },
            },
        };

        var result = ServiceRouteStationOrderResolver.ResolveServiceRouteStationOrder(
            sr, new List<MainRoute> { mainRoute });

        Assert.Equal(new[] { stC, stB, stA }, result);
    }

    [Fact]
    public void 正常系_複数segmentの境界駅は重複除去される()
    {
        var mainRouteId1 = new MainRouteId(1);
        var mainRouteId2 = new MainRouteId(2);
        var stA = new StationId(1);
        var stB = new StationId(2); // 境界駅
        var stC = new StationId(3);

        var mainRoute1 = MakeMainRoute(mainRouteId1, stA, stB);
        var mainRoute2 = MakeMainRoute(mainRouteId2, stB, stC);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "test-sr",
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId1, FromStationIndex = 0, ToStationIndex = 1 },
                new() { MainRouteId = mainRouteId2, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRouteStationOrderResolver.ResolveServiceRouteStationOrder(
            sr, new List<MainRoute> { mainRoute1, mainRoute2 });

        Assert.Equal(new[] { stA, stB, stC }, result);
    }

    [Fact]
    public void 境界駅由来MainRoute_境界駅は前segment側のMainRouteIdが採用される()
    {
        var mainRouteId1 = new MainRouteId(1);
        var mainRouteId2 = new MainRouteId(2);
        var stA = new StationId(1);
        var stB = new StationId(2); // 境界駅
        var stC = new StationId(3);

        var mainRoute1 = MakeMainRoute(mainRouteId1, stA, stB);
        var mainRoute2 = MakeMainRoute(mainRouteId2, stB, stC);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "test-sr",
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId1, FromStationIndex = 0, ToStationIndex = 1 },
                new() { MainRouteId = mainRouteId2, FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRouteStationOrderResolver.ResolveServiceRouteStationMainRoutes(
            sr, new List<MainRoute> { mainRoute1, mainRoute2 });

        Assert.Equal((stA, mainRouteId1), result[0]);
        Assert.Equal((stB, mainRouteId1), result[1]); // 境界駅はmainRouteId1側が採用される
        Assert.Equal((stC, mainRouteId2), result[2]);
    }

    [Fact]
    public void 異常系_MainRouteIdが存在しないsegmentはスキップされる()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "test-sr",
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = new MainRouteId(999), FromStationIndex = 0, ToStationIndex = 1 },
            },
        };

        var result = ServiceRouteStationOrderResolver.ResolveServiceRouteStationOrder(
            sr, new List<MainRoute> { mainRoute });

        Assert.Empty(result);
    }

    [Fact]
    public void 異常系_範囲外インデックスのsegmentは空扱いになる()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB);

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "test-sr",
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = 0, ToStationIndex = 5 },
            },
        };

        var result = ServiceRouteStationOrderResolver.ResolveServiceRouteStationOrder(
            sr, new List<MainRoute> { mainRoute });

        Assert.Empty(result);
    }
}
