using DiaEditCore.Algorithm;

using DiaEditCore.Model;
using DiaEditCore.Model.Routes;
using DiaEditCore.Model.Stations;
using DiaEditCore.Model.TimeTable;

using Xunit;

namespace DiaEditCore.Tests.Algorithm;

public class StopPatternResolverTests
{
    private static MainRoute MakeMainRoute(MainRouteId id, params StationId[] stations)
        => new()
        {
            Id = id,
            Name = new DisplayName { Name = "test-main-route" },
            StationOrder = stations.ToList(),
        };

    private static Station MakeStation(StationId id, string name)
        => new()
        {
            Id = id,
            DisplayName = new DisplayName { Name = name },
            Type = StationType.Standard,
        };

    private static ServiceRoute MakeSingleSegmentServiceRoute(ServiceRouteId id, MainRouteId mainRouteId, int fromIndex, int toIndex)
        => new()
        {
            Id = id,
            Name = new DisplayName{ Name = "test-sr"},
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = mainRouteId, FromStationIndex = fromIndex, ToStationIndex = toIndex },
            },
        };

    // A-B-Cの3駅、ServiceRoute全区間(0->2)、Trainは全区間走行、BのみStop
    private static (Train train, ServiceRoute sr, MainRoute mainRoute, List<Station> stations)
        BuildBasicThreeStationCase()
    {
        var mainRouteId = new MainRouteId(1);
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(mainRouteId, stA, stB, stC);
        var sr = MakeSingleSegmentServiceRoute(new ServiceRouteId(1), mainRouteId, 0, 2);

        var train = new Train
        {
            Id = new TrainId(1),
            TrainNumber = "1001M",
            ServiceRouteId = sr.Id,
            TrainTypeId = new TrainTypeId(1),
            TrainTypeName = new DisplayName { Name = "普通" },
            Nickname = new DisplayName { Name = "" },
            DefaultVehicleTypeId = new VehicleTypeId(1),
            RunSegments = new List<TrainRunSegment>
            {
                new() { FromStationId = stA, ToStationId = stB, StationConnectionId = new StationConnectionId(1) },
                new() { FromStationId = stB, ToStationId = stC, StationConnectionId = new StationConnectionId(2) },
            },
            StopTimes = new Dictionary<StopKey, StopTime>
            {
                [new StopKey(stA, 0)] = new() { IsStop = true, DepartureSeconds = 100 },
                [new StopKey(stB, 0)] = new() { IsStop = true, ArrivalSeconds = 200, DepartureSeconds = 210 },
                [new StopKey(stC, 0)] = new() { IsStop = true, ArrivalSeconds = 300 },
            },
        };

        var stations = new List<Station> { MakeStation(stA, "A駅"), MakeStation(stB, "B駅"), MakeStation(stC, "C駅") };
        return (train, sr, mainRoute, stations);
    }

    [Fact]
    public void 正常系_全駅停車の場合すべてStopになる()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stations);

        Assert.Equal(3, result.Count);
        Assert.All(result, e => Assert.Equal(StopPatternMark.Stop, e.Mark));
    }

    [Fact]
    public void 正常系_StopTimeがあってもIsStopがfalseならPassになる()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();
        // B駅を通過扱いに変更
        var stB = stations[1].Id;
        train.StopTimes[new StopKey(stB, 0)] = new StopTime { IsStop = false, DepartureSeconds = 205 };

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stations);

        var bElement = result.Single(e => e.StationId == stB);
        Assert.Equal(StopPatternMark.Pass, bElement.Mark);
    }

    [Fact]
    public void 正常系_StopTime自体が存在しない駅はPassになる()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();
        var stB = stations[1].Id;
        train.StopTimes.Remove(new StopKey(stB, 0));

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stations);

        var bElement = result.Single(e => e.StationId == stB);
        Assert.Equal(StopPatternMark.Pass, bElement.Mark);
    }

    [Fact]
    public void 正常系_RunSegmentsに含まれない駅はOutOfRangeになる()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();
        // Trainの実際の走行区間をA-Bのみに短縮（Cへは走行しない）
        train.RunSegments = new List<TrainRunSegment>
        {
            new() { FromStationId = stations[0].Id, ToStationId = stations[1].Id, StationConnectionId = new StationConnectionId(1) },
        };

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stations);

        var cElement = result.Single(e => e.StationId == stations[2].Id);
        Assert.Equal(StopPatternMark.OutOfRange, cElement.Mark);
    }

    [Fact]
    public void 表示名解決_MainRouteのStationDisplayNameOverridesが優先される()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();
        var stB = stations[1].Id;
        mainRoute.StationDisplayNameOverrides[stB] = new DisplayName { Name = "直通先B駅" };

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stations);

        var bElement = result.Single(e => e.StationId == stB);
        Assert.Equal("直通先B駅", bElement.StationDisplayName.Name);
    }

    [Fact]
    public void 表示名解決_上書きが無ければStationのDisplayNameにフォールバックする()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();
        var stB = stations[1].Id;

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stations);

        var bElement = result.Single(e => e.StationId == stB);
        Assert.Equal("B駅", bElement.StationDisplayName.Name);
    }

    [Fact]
    public void 異常系_ServiceRouteIdが存在しない場合は空リストが返る()
    {
        var (train, _, mainRoute, stations) = BuildBasicThreeStationCase();
        train.ServiceRouteId = new ServiceRouteId(999);

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute>(), new List<MainRoute> { mainRoute }, stations);

        Assert.Empty(result);
    }

    [Fact]
    public void 異常系_Stationが見つからない駅は結果からスキップされる()
    {
        var (train, sr, mainRoute, stations) = BuildBasicThreeStationCase();
        var stB = stations[1].Id;
        var stationsWithoutB = stations.Where(s => s.Id != stB).ToList();

        var result = StopPatternResolver.ResolveStopPattern(
            train, new List<ServiceRoute> { sr }, new List<MainRoute> { mainRoute }, stationsWithoutB);

        Assert.Equal(2, result.Count);
        Assert.DoesNotContain(result, e => e.StationId == stB);
    }
}
