using DiaEditCore.Model;
using DiaEditCore.Serialization.Validation;
using Xunit;

namespace DiaEditCore.Tests.Validation;

public class ServiceRouteValidatorTests
{
    [Fact]
    public void FromIndexとToIndexが同一だと不合格()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "テスト系統",
            IsAutoGenerated = false,
            Segments = [new ServiceRouteSegment { MainRouteId = new MainRouteId(1), FromStationIndex = 0, ToStationIndex = 0 }],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("同一"));
    }

    [Fact]
    public void IsUnidirectionalFalseでPairedフィールドが設定されていると不合格()
    {
        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "テスト系統",
            IsAutoGenerated = false,
            Segments =
            [
                new ServiceRouteSegment
                {
                    MainRouteId = new MainRouteId(1),
                    FromStationIndex = 0,
                    ToStationIndex = 1,
                    IsUnidirectional = false,
                    PairedMainRouteId = new MainRouteId(2),
                },
            ],
        };
        var context = new ValidationContext();

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("Paired系フィールド"));
    }

    [Fact]
    public void 隣接Segmentの境界駅が不一致だと不合格()
    {
        var routeA = new MainRoute { Id = new MainRouteId(1), Name = new DisplayName { Name = "A線" }, StationOrder = [new StationId(1), new StationId(2)] };
        var routeB = new MainRoute { Id = new MainRouteId(2), Name = new DisplayName { Name = "B線" }, StationOrder = [new StationId(99), new StationId(3)] }; // 境界駅がA線末尾(2)と一致しない

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "テスト系統",
            IsAutoGenerated = false,
            Segments =
            [
                new ServiceRouteSegment { MainRouteId = routeA.Id, FromStationIndex = 0, ToStationIndex = 1 },
                new ServiceRouteSegment { MainRouteId = routeB.Id, FromStationIndex = 0, ToStationIndex = 1 },
            ],
        };
        var context = new ValidationContext { MainRoutes = [routeA, routeB] };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Contains(issues, i => i.Message.Contains("境界駅が不一致"));
    }

    [Fact]
    public void 境界駅が一致していれば合格()
    {
        var routeA = new MainRoute { Id = new MainRouteId(1), Name = new DisplayName { Name = "A線" }, StationOrder = [new StationId(1), new StationId(2)] };
        var routeB = new MainRoute { Id = new MainRouteId(2), Name = new DisplayName { Name = "B線" }, StationOrder = [new StationId(2), new StationId(3)] };

        var scA = new StationConnection { Id = new StationConnectionId(1), Name = "A下り", MainRouteId = routeA.Id, Direction = StationConnectionDirection.Down, Segments = [] };
        var scAUp = new StationConnection { Id = new StationConnectionId(2), Name = "A上り", MainRouteId = routeA.Id, Direction = StationConnectionDirection.Up, Segments = [] };
        var scB = new StationConnection { Id = new StationConnectionId(3), Name = "B下り", MainRouteId = routeB.Id, Direction = StationConnectionDirection.Down, Segments = [] };
        var scBUp = new StationConnection { Id = new StationConnectionId(4), Name = "B上り", MainRouteId = routeB.Id, Direction = StationConnectionDirection.Up, Segments = [] };

        var sr = new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = "テスト系統",
            IsAutoGenerated = false,
            Segments =
            [
                new ServiceRouteSegment { MainRouteId = routeA.Id, FromStationIndex = 0, ToStationIndex = 1 },
                new ServiceRouteSegment { MainRouteId = routeB.Id, FromStationIndex = 0, ToStationIndex = 1 },
            ],
        };
        var context = new ValidationContext { MainRoutes = [routeA, routeB], StationConnections = [scA, scAUp, scB, scBUp] };

        var issues = new ServiceRouteValidator().Validate(sr, context);

        Assert.Empty(issues);
    }
}