using DiaEditCore.Model;
using DiaEditCore.Serialization.Validation;
using Xunit;

namespace DiaEditCore.Tests.Validation;

public class TrainValidatorTests
{
    private static ServiceRoute MakeServiceRoute(int id) => new()
    {
        Id = new ServiceRouteId(id),
        Name = "テスト運行系統",
        IsAutoGenerated = false,
        Segments = [],
    };

    private static TrainType MakeTrainType(int id) => new()
    {
        Id = new TrainTypeId(id),
        Name = new DisplayName { Name = "普通" },
        DiagramColor = "#000000",
        DiagramLineStyle = LineStyle.Solid,
        SortOrder = 0,
    };

    private static VehicleType MakeVehicleType(int id) => new()
    {
        Id = new VehicleTypeId(id),
        Name = "E235系",
        LengthM = 20.0,
        BaseCarTemplate = [new CarRoleSlot { CarTypeCode = "クハE234" }],
    };

    private static Train MakeValidTrain(int id, string trainNumber = "1234M") => new()
    {
        Id = new TrainId(id),
        TrainNumber = trainNumber,
        ServiceRouteId = new ServiceRouteId(1),
        TrainTypeId = new TrainTypeId(1),
        TrainTypeName = new DisplayName { Name = "普通" },
        Nickname = new DisplayName { Name = "" },
        DefaultVehicleTypeId = new VehicleTypeId(1),
    };

    private static ValidationContext MakeBaseContext(params Train[] trains) => new()
    {
        ServiceRoutes = [MakeServiceRoute(1)],
        TrainTypes = [MakeTrainType(1)],
        VehicleTypes = [MakeVehicleType(1)],
        Trains = trains,
    };

    [Fact]
    public void 必須参照が全て揃っていれば合格()
    {
        var train = MakeValidTrain(1);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void TrainNumberが空なら不合格()
    {
        var train = MakeValidTrain(1, trainNumber: "");
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("TrainNumberが空"));
    }

    [Fact]
    public void TrainNumberが他のTrainと重複していれば不合格()
    {
        var trainA = MakeValidTrain(1, trainNumber: "1234M");
        var trainB = MakeValidTrain(2, trainNumber: "1234M");
        var context = MakeBaseContext(trainA, trainB);

        var issues = new TrainValidator().Validate(trainA, context);

        Assert.Contains(issues, i => i.Message.Contains("重複している"));
    }

    [Fact]
    public void ServiceRouteIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.ServiceRouteId = new ServiceRouteId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("ServiceRouteId"));
    }

    [Fact]
    public void TrainTypeIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.TrainTypeId = new TrainTypeId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("TrainTypeId"));
    }

    [Fact]
    public void DefaultVehicleTypeIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.DefaultVehicleTypeId = new VehicleTypeId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("DefaultVehicleTypeId"));
    }

    [Fact]
    public void SourceTrainIdが自分自身なら不合格()
    {
        var train = MakeValidTrain(1);
        train.SourceTrainId = train.Id;
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("自分自身"));
    }

    [Fact]
    public void SourceTrainIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.SourceTrainId = new TrainId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("SourceTrainId(") && i.Message.Contains("が存在しない"));
    }

    [Fact]
    public void SourceTrainIdが多段参照なら不合格()
    {
        var grandParent = MakeValidTrain(1, "0001M");
        var parent = MakeValidTrain(2, "0002M");
        parent.SourceTrainId = grandParent.Id;
        var child = MakeValidTrain(3, "0003M");
        child.SourceTrainId = parent.Id;
        var context = MakeBaseContext(grandParent, parent, child);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Contains(issues, i => i.Message.Contains("多段参照禁止"));
    }

    [Fact]
    public void SourceTrainIdが単段参照なら合格()
    {
        var parent = MakeValidTrain(1, "0001M");
        var child = MakeValidTrain(2, "0002M");
        child.SourceTrainId = parent.Id;
        var context = MakeBaseContext(parent, child);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void RunSegmentsのStationConnectionIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = new StationId(1),
            ToStationId = new StationId(2),
            StationConnectionId = new StationConnectionId(999),
        });
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("RunSegments[0]"));
    }

    [Fact]
    public void StopTimesの矛盾がWorks経由で伝播する()
    {
        var train = MakeValidTrain(1);
        train.StopTimes[new StopKey(new StationId(1), 0)] = new StopTime
        {
            Works = [new StationWork { Type = StationWorkType.None }],
        };
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("StopTimes[") && i.Message.Contains("None"));
    }
}
