namespace DiaEditCore.Tests.Session;

using DiaEditCore.Commands;
using DiaEditCore.Model;
using DiaEditCore.Model.Routes;
using DiaEditCore.Session;

using Xunit;

public class ProjectSessionTests
{
    private static readonly ValidationRules DefaultValidationRules = new(
        MinDwellTimeSec: null,
        MinHeadwaySec: null,
        MinTurnaroundSec: null,
        TrackEntryMarginSec: null,
        TrackPassMarginSec: null,
        EnableConflictDetection: true,
        EnableCarLengthCheck: true);

    private static ProjectFile MakeEmptyProject() => new()
    {
        SchemaVersion = 1,
        ProjectSettings = new ProjectSettings(DefaultValidationRules),
    };

    private static StationConnection MakeSc(int id, int mainRouteId, params int[] segIds) => new()
    {
        Id = new StationConnectionId(id),
        Name = $"SC{id}",
        MainRouteId = new MainRouteId(mainRouteId),
        Direction = StationConnectionDirection.Down,
        Segments = segIds.Select(s => new StationConnectionSegmentId(s)).ToList(),
    };

    private static StationConnectionSegment MakeSeg(int id, int fromStation, int toStation, int fromEp, int toEp) => new()
    {
        Id = new StationConnectionSegmentId(id),
        StationIdA = new StationId(fromStation),
        StationIdB = new StationId(toStation),
        EntryPointIdA = new EntryPointId(fromEp),
        EntryPointIdB = new EntryPointId(toEp),
        MainRouteId = new MainRouteId(1),
    };

    [Fact]
    public void Load前にGetCacheを呼ぶと例外になる()
    {
        var session = new ProjectSession(new CommandInvoker());

        Assert.Throws<InvalidOperationException>(() => session.GetCache());
    }

    [Fact]
    public void Load直後にGetCacheを呼ぶとdirtyフラグを介さず即座にキャッシュが構築されている()
    {
        var project = MakeEmptyProject();
        project.StationConnectionSegments.Add(MakeSeg(100, 1, 2, 10, 20));
        project.StationConnections.Add(MakeSc(1, mainRouteId: 1, 100));

        var session = new ProjectSession(new CommandInvoker());
        session.Load(project);

        var cache = session.GetCache();

        // RebuildAll内で構築される軽量インデックスの1つが機能していることを確認
        Assert.True(cache.MainRouteConnectionIndex.ContainsKey(new MainRouteId(1)));
    }

    [Fact]
    public void ServiceRoutesByMainRouteIndexがLoad後に正しく構築される()
    {
        // v12.20で発覚した回帰バグ（RebuildCacheIfDirty側の再構築呼び出し漏れ）の再発防止テスト。
        // ServiceRoutesByMainRouteIndexはTimeTableSetCache.RebuildAll側ではClearのみされ、
        // 構築自体はProjectSession.RebuildCacheIfDirtyの責務であるため、他インデックスと違い
        // 「RebuildAllを呼んだだけでは検出できない」タイプの不具合だった。
        var project = MakeEmptyProject();
        project.ServiceRoutes.Add(new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName { Name = "Test" },
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new()
                {
                    MainRouteId = new MainRouteId(1),
                    FromStationIndex = 0,
                    ToStationIndex = 1,
                }
            },
        });

        var session = new ProjectSession(new CommandInvoker());
        session.Load(project);

        var cache = session.GetCache();

        Assert.True(cache.ServiceRoutesByMainRouteIndex.TryGetValue(new MainRouteId(1), out var srIds));
        Assert.Contains(new ServiceRouteId(1), srIds!);
    }

    [Fact]
    public void GetCacheを複数回呼んでもServiceRoutesByMainRouteIndexは空にならない()
    {
        // 修正前は、RebuildCacheIfDirtyが呼ばれるたび（＝2回目以降のGetCache呼び出しのたび）に
        // 「TimeTableSetCache.RebuildAll内でClearされるが再構築コードが無い」状態になり、
        // 2回目のGetCache()呼び出し以降このインデックスが常に空になっていた。
        var project = MakeEmptyProject();
        project.ServiceRoutes.Add(new ServiceRoute
        {
            Id = new ServiceRouteId(1),
            Name = new DisplayName { Name = "Test" },
            IsAutoGenerated = false,
            Segments = new List<ServiceRouteSegment>
            {
                new() { MainRouteId = new MainRouteId(1), FromStationIndex = 0, ToStationIndex = 1 }
            },
        });

        var invoker = new CommandInvoker();
        var session = new ProjectSession(invoker);
        session.Load(project);

        // 1回目
        Assert.NotEmpty(session.GetCache().ServiceRoutesByMainRouteIndex);

        // 何らかのコマンド実行でdirty化されたと仮定し、再度dirty化をシミュレートする
        // （OnChangedはinterfaceの明示的実装のためICacheChangeObserver経由で呼ぶ）
        ((DiaEditCore.ChangeNotification.ICacheChangeObserver)session)
            .OnChanged(new HashSet<ObjectId> { new MainRouteObjectId(new MainRouteId(1)) });

        // 2回目（dirty再構築後）でも空にならないことを確認
        Assert.NotEmpty(session.GetCache().ServiceRoutesByMainRouteIndex);
    }

    [Fact]
    public void OnChangedが呼ばれるとキャッシュがdirty化され次回GetCacheで再構築される()
    {
        var project = MakeEmptyProject();
        var session = new ProjectSession(new CommandInvoker());
        session.Load(project);

        // Load直後の状態を確認（MainRouteId(2)関連のデータはまだ存在しない）
        Assert.False(session.GetCache().MainRouteConnectionIndex.ContainsKey(new MainRouteId(2)));

        project.StationConnectionSegments.Add(MakeSeg(200, 3, 4, 30, 40));
        project.StationConnections.Add(MakeSc(2, mainRouteId: 2, 200));

        // OnChangedを呼ぶ前は、_cacheDirtyがfalseのままのため再構築が走らない
        // （GetCache()を呼んでも、projectへ直接追加したデータはまだ反映されない）。
        // これはGetCache()が毎回_cacheの同一インスタンスを返す実装のため、
        // before/after変数で参照を保持して比較する形では検証できない
        // （後の変更が古い変数からも見えてしまう）。dirty化前後で都度アサートする形に統一する。
        Assert.False(session.GetCache().MainRouteConnectionIndex.ContainsKey(new MainRouteId(2)));

        ((DiaEditCore.ChangeNotification.ICacheChangeObserver)session)
            .OnChanged(new HashSet<ObjectId> { new StationConnectionObjectId(new StationConnectionId(2)) });

        // OnChanged後は_cacheDirty=trueとなり、次のGetCache()で再構築されて反映される
        Assert.True(session.GetCache().MainRouteConnectionIndex.ContainsKey(new MainRouteId(2)));
    }

    [Fact]
    public void Loadを再度呼ぶと以前のキャッシュ内容が引き継がれず新規プロジェクトのみが反映される()
    {
        var project1 = MakeEmptyProject();
        project1.StationConnectionSegments.Add(MakeSeg(100, 1, 2, 10, 20));
        project1.StationConnections.Add(MakeSc(1, mainRouteId: 1, 100));

        var session = new ProjectSession(new CommandInvoker());
        session.Load(project1);
        Assert.True(session.GetCache().MainRouteConnectionIndex.ContainsKey(new MainRouteId(1)));

        var project2 = MakeEmptyProject();
        session.Load(project2);

        Assert.False(session.GetCache().MainRouteConnectionIndex.ContainsKey(new MainRouteId(1)));
    }

    [Fact]
    public void FloorUnitDependentIndexとDepartureByStationTrackIndexとStopKeyReferenceIndexもLoad後に構築される()
    {
        // Rebuild漏れの再発防止として、既に配線済みだった3インデックスについても
        // 実際に非nullの辞書として存在すること（＝クラッシュしないこと）を確認しておく回帰テスト。
        var project = MakeEmptyProject();

        var session = new ProjectSession(new CommandInvoker());
        session.Load(project);

        var cache = session.GetCache();

        Assert.NotNull(cache.FloorUnitDependentIndex);
        Assert.NotNull(cache.DepartureByStationTrackIndex);
        Assert.NotNull(cache.StopKeyReferenceIndex);
        Assert.NotNull(cache.ServiceRoutesByMainRouteIndex);
    }
}