using DiaEditCore.Model;
using DiaEditCore.Model.Routes;
using DiaEditCore.Model.Cars;
using DiaEditCore.Model.TimeTable;
using DiaEditCore.Model.TimeTable.Trains;

using DiaEditCore.Serialization.Validation;
using DiaEditCore.Serialization.Validation.TimeTable.Trains;

using Xunit;

namespace DiaEditCore.Tests.Serialization.Validation.TimeTable.Trains;
public class TrainValidatorTests
{
    private static MainRoute MakeMainRoute(int id, params StationId[] stationOrder) => new()
    {
        Id = new MainRouteId(id),
        Name = new DisplayName { Name = "テスト本線" },
        StationOrder = stationOrder.ToList(),
        IsLoop = false,
    };

    private static ServiceRoute MakeServiceRouteWithSegment(int id, int mainRouteId, int fromIndex, int toIndex) => new()
    {
        Id = new ServiceRouteId(id),
        Name = new DisplayName { Name = "テスト系統" },
        IsAutoGenerated = false,
        Segments = [new ServiceRouteSegment { MainRouteId = new MainRouteId(mainRouteId), FromStationIndex = fromIndex, ToStationIndex = toIndex }],
    };
    private static ServiceRoute MakeServiceRoute(int id) => new()
    {
        Id = new ServiceRouteId(id),
        Name = new DisplayName { Name = "テスト系統" },
        IsAutoGenerated = false,
        Segments = [],
    };

    private static TrainType MakeTrainType(int id) => new()
    {
        Id = new TrainTypeId(id),
        Name = new DisplayName { Name = "普通" },
        DiagramColor = "#000000",
        DiagramLineStyle = LineStyle.Solid,
        SortOrder = 0,
    };

    private static VehicleType MakeVehicleType(int id) => new()
    {
        Id = new VehicleTypeId(id),
        Name = "E235系",
    };

    private static Train MakeValidTrain(int id, string trainNumber = "1234M") => new()
    {
        Id = new TrainId(id),
        TimeTableSetId = new TimeTableSetId(1),
        TrainNumber = trainNumber,
        ServiceRouteId = new ServiceRouteId(1),
        TrainTypeId = new TrainTypeId(1),
        TrainTypeName = new DisplayName { Name = "普通" },
        Nickname = new DisplayName { Name = "" },
        DefaultVehicleTypeId = new VehicleTypeId(1),
    };

    private static StationConnectionSegment MakeSegment(int id, StationId from, StationId to, int mainRouteId = 1) => new()
    {
        Id = new StationConnectionSegmentId(id),
        FromStationId = from,
        ToStationId = to,
        FromEntryPointId = new EntryPointId(id * 10 + 1),
        ToEntryPointId = new EntryPointId(id * 10 + 2),
        MainRouteId = new MainRouteId(mainRouteId),
    };

    private static StationConnection MakeConnection(int id, int mainRouteId, StationConnectionDirection direction, params StationConnectionSegmentId[] segmentIds) => new()
    {
        Id = new StationConnectionId(id),
        Name = "test-sc",
        MainRouteId = new MainRouteId(mainRouteId),
        Direction = direction,
        Segments = segmentIds.ToList(),
    };

    private static ValidationContext MakeBaseContext(
        Train[] trains,
        StationConnection[]? stationConnections = null,
        StationConnectionSegment[]? stationConnectionSegments = null,
        TimeTableSet[]? timeTableSets = null,
        DiagramRevision[]? diagramRevisions = null,
        ServiceRoute[]? serviceRoutes = null,
        MainRoute[]? mainRoutes = null) => new()
    {
        ServiceRoutes = serviceRoutes ?? [MakeServiceRoute(1)],
        MainRoutes = mainRoutes ?? [],
        TrainTypes = [MakeTrainType(1)],
        VehicleTypes = [MakeVehicleType(1)],
        Trains = trains,
        StationConnections = stationConnections ?? [],
        StationConnectionSegments = stationConnectionSegments ?? [],
        TimeTableSets = timeTableSets ?? [],
        DiagramRevisions = diagramRevisions ?? [],
    };

    private static ValidationContext MakeBaseContext(params Train[] trains) => MakeBaseContext(trains, null, null);

    [Fact]
    public void 必須参照が全て揃っていれば合格()
    {
        var train = MakeValidTrain(1);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void TrainNumberが空なら不合格()
    {
        var train = MakeValidTrain(1, trainNumber: "");
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("TrainNumberが空"));
    }

    [Fact]
    public void TrainNumberが他のTrainと重複していれば不合格()
    {
        var trainA = MakeValidTrain(1, trainNumber: "1234M");
        var trainB = MakeValidTrain(2, trainNumber: "1234M");
        var context = MakeBaseContext(trainA, trainB);

        var issues = new TrainValidator().Validate(trainA, context);

        Assert.Contains(issues, i => i.Message.Contains("重複している"));
    }

    [Fact]
    public void ServiceRouteIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.ServiceRouteId = new ServiceRouteId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("ServiceRouteId"));
    }

    [Fact]
    public void TrainTypeIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.TrainTypeId = new TrainTypeId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("TrainTypeId"));
    }

    [Fact]
    public void DefaultVehicleTypeIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.DefaultVehicleTypeId = new VehicleTypeId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("DefaultVehicleTypeId"));
    }

    [Fact]
    public void SourceTrainIdが自分自身なら不合格()
    {
        var train = MakeValidTrain(1);
        train.SourceTrainId = train.Id;
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("自分自身"));
    }

    [Fact]
    public void SourceTrainIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.SourceTrainId = new TrainId(999);
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("SourceTrainId(") && i.Message.Contains("が存在しない"));
    }

    [Fact]
    public void SourceTrainIdが多段参照なら不合格()
    {
        var grandParent = MakeValidTrain(1, "0001M");
        var parent = MakeValidTrain(2, "0002M");
        parent.SourceTrainId = grandParent.Id;
        var child = MakeValidTrain(3, "0003M");
        child.SourceTrainId = parent.Id;
        var context = MakeBaseContext(grandParent, parent, child);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Contains(issues, i => i.Message.Contains("多段参照禁止"));
    }

    [Fact]
    public void SourceTrainIdが単段参照なら合格()
    {
        var parent = MakeValidTrain(1, "0001M");
        var child = MakeValidTrain(2, "0002M");
        child.SourceTrainId = parent.Id;
        var context = MakeBaseContext(parent, child);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Empty(issues);
    }

    // --- 8.2節項目6：baseTimeTableSet内はSourceTrainId=null必須 ---

    [Fact]
    public void baseTimeTableSet所属でSourceTrainIdを持つと不合格()
    {
        var parent = MakeValidTrain(1, "0001M");
        var child = MakeValidTrain(2, "0002M");
        child.SourceTrainId = parent.Id;

        var timeTableSet = new TimeTableSet { Id = new TimeTableSetId(1), Name = "base", TrainIds = [child.Id] };
        var diagramRevision = new DiagramRevision
        {
            Id = new DiagramRevisionId(1),
            Name = "リビジョンA",
            TimeTableSetIds = [timeTableSet.Id],
            BaseTimeTableSetId = timeTableSet.Id,
        };
        var context = MakeBaseContext([parent, child], timeTableSets: [timeTableSet], diagramRevisions: [diagramRevision]);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Contains(issues, i => i.Message.Contains("baseTimeTableSet") && i.Message.Contains("SourceTrainId"));
    }

    [Fact]
    public void baseTimeTableSet所属でもSourceTrainIdが無ければ合格()
    {
        var train = MakeValidTrain(1);

        var timeTableSet = new TimeTableSet { Id = new TimeTableSetId(1), Name = "base", TrainIds = [train.Id] };
        var diagramRevision = new DiagramRevision
        {
            Id = new DiagramRevisionId(1),
            Name = "リビジョンA",
            TimeTableSetIds = [timeTableSet.Id],
            BaseTimeTableSetId = timeTableSet.Id,
        };
        var context = MakeBaseContext([train], timeTableSets: [timeTableSet], diagramRevisions: [diagramRevision]);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void 非baseTimeTableSet所属でSourceTrainIdを持っていてもエラーなし()
    {
        var parent = MakeValidTrain(1, "0001M");
        var child = MakeValidTrain(2, "0002M");
        child.SourceTrainId = parent.Id;

        // TimeTableSetは存在するが、どのDiagramRevisionからもBaseTimeTableSetIdとして参照されていない
        var timeTableSet = new TimeTableSet { Id = new TimeTableSetId(1), Name = "非base", TrainIds = [child.Id] };
        var diagramRevision = new DiagramRevision
        {
            Id = new DiagramRevisionId(1),
            Name = "リビジョンA",
            TimeTableSetIds = [timeTableSet.Id],
            BaseTimeTableSetId = null,
        };
        var context = MakeBaseContext([parent, child], timeTableSets: [timeTableSet], diagramRevisions: [diagramRevision]);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void どのTimeTableSetにも属さないTrainはSourceTrainIdを持っていても判定不能としてスキップされる()
    {
        var parent = MakeValidTrain(1, "0001M");
        var child = MakeValidTrain(2, "0002M");
        child.SourceTrainId = parent.Id;

        // TimeTableSets自体は存在するが、childはどのTrainIdsにも含まれていない
        var timeTableSet = new TimeTableSet { Id = new TimeTableSetId(1), Name = "base", TrainIds = [] };
        var diagramRevision = new DiagramRevision
        {
            Id = new DiagramRevisionId(1),
            Name = "リビジョンA",
            TimeTableSetIds = [timeTableSet.Id],
            BaseTimeTableSetId = timeTableSet.Id,
        };
        var context = MakeBaseContext([parent, child], timeTableSets: [timeTableSet], diagramRevisions: [diagramRevision]);

        var issues = new TrainValidator().Validate(child, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void RunSegmentsのStationConnectionIdが存在しなければ不合格()
    {
        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = new StationId(1),
            ToStationId = new StationId(2),
            StationConnectionId = new StationConnectionId(999),
        });
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("RunSegments[0]"));
    }

    [Fact]
    public void StopTimesの矛盾がWorks経由で伝播する()
    {
        var train = MakeValidTrain(1);
        train.StopTimesInternal[new StopKey(new StationId(1), 0)] = new StopTime
        {
            Works = [new StationWork { Type = StationWorkType.None }],
        };
        var context = MakeBaseContext(train);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("StopTimes[") && i.Message.Contains("None"));
    }

    // --- 8.2節項目8：RunSegmentsの深い整合性検証（EntryPointSequenceResolver経由） ---

    [Fact]
    public void RunSegmentsのホップが参照先StationConnectionの実際の駅間と一致すれば合格()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var seg = MakeSegment(1, stA, stB);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = stA,
            ToStationId = stB,
            StationConnectionId = sc.Id,
        });
        var context = MakeBaseContext([train], [sc], [seg]);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void RunSegmentsのホップが参照先StationConnectionの実際の駅間と一致しなければ不合格()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stX = new StationId(99); // StationConnectionがカバーしない駅
        var seg = MakeSegment(1, stA, stB);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg.Id);

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = stA,
            ToStationId = stX, // 実際のSCのホップ（A→B）と食い違う
            StationConnectionId = sc.Id,
        });
        var context = MakeBaseContext([train], [sc], [seg]);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("RunSegments[0]") && i.Message.Contains("一致しない"));
    }

    [Fact]
    public void 複数ホップで構成されるStationConnectionでも内部の1ホップに一致すれば合格()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var seg1 = MakeSegment(1, stA, stB);
        var seg2 = MakeSegment(2, stB, stC);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down, seg1.Id, seg2.Id);

        var train = MakeValidTrain(1);
        // B→CというホップはSC全体の一部（2番目のsegment）としてのみ存在する
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = stB,
            ToStationId = stC,
            StationConnectionId = sc.Id,
        });
        var context = MakeBaseContext([train], [sc], [seg1, seg2]);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Empty(issues);
    }

    [Fact]
    public void StationConnectionは存在するがSegmentsが空なら不合格()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var sc = MakeConnection(1, 1, StationConnectionDirection.Down); // segments空

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment
        {
            FromStationId = stA,
            ToStationId = stB,
            StationConnectionId = sc.Id,
        });
        var context = MakeBaseContext([train], [sc], []);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("RunSegments[0]") && i.Message.Contains("一致しない"));
    }
    [Fact]
    public void RunSegmentsがServiceRouteの現在のStationOrderと一致すれば合格()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var mainRoute = MakeMainRoute(1, stA, stB, stC);
        var serviceRoute = MakeServiceRouteWithSegment(1, mainRouteId: 1, fromIndex: 0, toIndex: 2);

        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = stA, ToStationId = stB, StationConnectionId = new StationConnectionId(1) });
        train.RunSegments.Add(new TrainRunSegment { FromStationId = stB, ToStationId = stC, StationConnectionId = new StationConnectionId(1) });

        var context = MakeBaseContext([train], serviceRoutes: [serviceRoute], mainRoutes: [mainRoute]);

        var issues = new TrainValidator().Validate(train, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("StationOrder"));
    }

    [Fact]
    public void StationOrder変更後にRunSegmentsが未同期なら不合格()
    {
        var stA = new StationId(1);
        var stB = new StationId(2);
        var stC = new StationId(3);
        var stD = new StationId(4); // StationOrder変更で新たに挿入された駅
        var mainRoute = MakeMainRoute(1, stA, stB, stD, stC); // B-C間にDが挿入された、という想定
        var serviceRoute = MakeServiceRouteWithSegment(1, mainRouteId: 1, fromIndex: 0, toIndex: 3);

        var train = MakeValidTrain(1);
        // Train側はまだ古い駅順（A→B→C）のまま同期していない
        train.RunSegments.Add(new TrainRunSegment { FromStationId = stA, ToStationId = stB, StationConnectionId = new StationConnectionId(1) });
        train.RunSegments.Add(new TrainRunSegment { FromStationId = stB, ToStationId = stC, StationConnectionId = new StationConnectionId(1) });

        var context = MakeBaseContext([train], serviceRoutes: [serviceRoute], mainRoutes: [mainRoute]);

        var issues = new TrainValidator().Validate(train, context);

        Assert.Contains(issues, i => i.Message.Contains("StationOrder") && i.Message.Contains("同期"));
    }

    [Fact]
    public void ServiceRouteにSegmentsが未設定なら陳腐化チェックはスキップされ合格()
    {
        // MakeServiceRoute(1)のデフォルトはSegments=[]。ServiceRoute自体が未構築なだけであり、
        // 「StationOrder変更によりTrainが陳腐化した」ケースとは区別する（ServiceRouteValidator側の責務）。
        var train = MakeValidTrain(1);
        train.RunSegments.Add(new TrainRunSegment { FromStationId = new StationId(1), ToStationId = new StationId(2), StationConnectionId = new StationConnectionId(1) });

        var context = MakeBaseContext([train]); // serviceRoutes未指定＝デフォルト(Segments=[])

        var issues = new TrainValidator().Validate(train, context);

        Assert.DoesNotContain(issues, i => i.Message.Contains("StationOrder"));
    }
}